### ISSUE TITLE
tileserver-gl raster tile attributions don't show up

### ISSUE THREAD

**Issue by boonboonsiri** [maptiler/tileserver-gl#1004]
## **Issue**
I'm not sure if this is intentional, but the attributions (bottom right) doesn't show up for generated raster tiles. They show up in both the `tilejson` and leaflet map demo but doesn't show up for the actual rendered raster image.

<img width="534" alt="image" src="https://github.com/maptiler/tileserver-gl/assets/35120291/dd0d9b01-c727-41a5-95bc-5b9097ff5f11">

<img width="1000" alt="image" src="https://github.com/maptiler/tileserver-gl/assets/35120291/e57eafe6-6de8-483f-aa2a-a701512db99a">

<img width="1281" alt="image" src="https://github.com/maptiler/tileserver-gl/assets/35120291/7a7e8019-c1a8-40a4-8797-60df385b3a7f">

Config used looks something like this
```json

{
  "options": {
    "paths": {
      "root": "",
      "fonts": "fonts",
      "sprites": "sprites",
      "styles": "styles"
    },
    "maxScaleFactor": 3,
    "maxSize": 2048,
    "pbfAlias": "pbf",
    "serveAllFonts": true,
    "serveAllStyles": false,
    "serveStaticMaps": true,
    "allowRemoteMarkerIcons": false,
    "tileMargin": 0,
    "attribution": "radar upper"
  },
  "styles": {
    "radar-dark-v1": {
      "style": "radar-dark-v1.json",
      "tilejson": {
        "type": "baselayer",
        "attribution": "test"
      }
    }
  }
}
```

&nbsp;
&nbsp;
&nbsp;

### **Reproduce**
the default attribution also doesn't show up, not just the custom attribution and can be reproduced like this
```
wget https://github.com/maptiler/tileserver-gl/releases/download/v1.3.0/test_data.zip
unzip test_data.zip
docker run --rm -it -v $(pwd):/data -p 8080:8080 maptiler/tileserver-gl
[in your browser, visit http://[server ip]:8080]
```
and then the generated tile [image](http://[::]:8080/styles/klokantech-basic/static/8.5,47.3881,10.7/1000x1000.png) has no attribution

<img width="2095" alt="image" src="https://github.com/maptiler/tileserver-gl/assets/35120291/8a2c573c-f103-44f1-bbf9-ee6cfbe4f153">

### **About**

Macos: 13.5.1
Docker: 4.24.0 
TileserverGL: 4.5.1

**Comment by acalcutt** [comment]
You are right, static images don't have attibution 

In Vector view, TileJSON gets passed to maplibre-gl-js and it displays the attribution. In Raster view, maplibre-native does the rendering but leaflet is showing the attribution [based on the TileJSON](https://github.com/maptiler/tileserver-gl/blob/master/public/templates/viewer.tmpl#L84-L121)

In Static view however, Maplibre-Native is making the image and tileserver-gl is passing it back to the user. Maplibre-Native processes the TileJSON, but it doesn't include anything to display the attibution.

An workaround right now might be to use [WATERMARK](https://maptiler-tileserver.readthedocs.io/en/latest/config.html#watermark), which looks something like
![249139753-3269cd8e-5942-4237-848d-8dbdf6a2567d](https://github.com/maptiler/tileserver-gl/assets/3792408/968d9590-4e8e-4b94-840e-a91a8c9a5661)

You could also read the tilejson for the style and display it in your own app, but that is a bit of a pain.


If we were to add attribution to static imges, we could possibly add code similar to watermark, which would draw the test over the image maplibre-native generates.
https://github.com/maptiler/tileserver-gl/blob/master/src/serve_rendered.js#L760-L771

**Comment by boonboonsiri** [comment]
Ah okay okay yeah I'm open to many ideas. Just want to attribute everyone correctly.

If this [PR](https://github.com/maptiler/tileserver-gl/pull/1005) satisfies your needs then I think this issue is good

**Comment by acalcutt** [comment]
Do you have any opinion on https://github.com/maptiler/tileserver-gl/pull/1005 ? do you think that would fix your needs. I plan to approve it, but like to hear what people think.

**Comment by boonboonsiri** [comment]
https://github.com/maptiler/tileserver-gl/issues/1004#issuecomment-1749716615 is perfect

**Comment by boonboonsiri** [comment]
Closed with https://github.com/maptiler/tileserver-gl/issues/1004#issuecomment-1749716615
