### ISSUE TITLE
tileserver-gl-light with leaflet

### ISSUE THREAD

**Issue by akram-mhss** [maptiler/tileserver-gl#1012]
Hello, I had been using TileServer in Docker successfully, but I needed to switch to TileServer GL Light since TileServer GL native doesn't support Windows. However, with TileServer GL Light, I can only display vector tiles using the following link:

tileserver-gl-light link:
http://localhost:8080/styles/basic-preview/?vector#3.66/23.88/-2.12

code:
L.tileLayer('http://localhost:8080/styles/basic-preview/{z}/{x}/{y}.png', {
    maxZoom: 19,
}).addTo(map);

Is there a way to display raster tiles in my project with TileServer GL Light?
or i need to edit in the code to supprt vector or something like this

**Comment by acalcutt** [comment]
TileServer Light doesn't support raster tiles. the main difference in the light version is lack of maplibre-native, which is what produces those raster tiles.

It is possible to get the non-light version to work in windows, but it needs few tweaks. I use this in development sometimes.
1.) clone the repo
2.) In src/serve_rendered.js , reverse sharp and canvas imports at https://github.com/maptiler/tileserver-gl/blob/master/src/serve_rendered.js#L9-L10
3.) In package.json, lower you version of sharp. I have been using `"sharp": "0.29.3",` in testing
4.) nvm install 18.18.1 (I am using nvm for windows to install npm https://github.com/coreybutler/nvm-windows )
5.) npm install  
6.) make sure you have the latest c++ redistributable https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

With these changes tileserver-gl should on windows
![image](https://github.com/maptiler/tileserver-gl/assets/3792408/15ffa6f3-0ce5-43d8-ad0d-f9bae44cba9d)

**Comment by acalcutt** [comment]
Either the full or light docker versions of tileserver-gl should work with the docker version, provided you adjust the to use a real path in your command and not $(pwd)

**Comment by akram-mhss** [comment]
Thank you so much for your assistance, it worked perfectly

**Comment by acalcutt** [comment]
Awesome. one of these days I would like to support windows better, but sharp and canvas has been a problem. I had submitted a workaround in https://github.com/maptiler/tileserver-gl/pull/822 but it seems to no longer work now.

Maybe for now I should make a windows branch with the few tweaks windows needs to work...just so people have any easy way to use it on windows.
