### ISSUE TITLE
TileServer-GL Issue on Windows Server 2022

### ISSUE THREAD

**Issue by akram-mhss** [maptiler/tileserver-gl#1020]
When I fire up TileServer-GL on my Windows Server 2022, everything seems fine and dandy. But the problem kicks in when I try to access specific URLs like "https://localhost:8080" or "https://localhost/styles/basic-preview/1/0/1.png." When I do that, the server running in the command prompt mysteriously shuts down, and no error logs get generated. Instead, the console spits out this message: "GET https://144.91.**.***:444/styles/basic-preview/6/31/30.png 502 (Bad Gateway)."

I'm stumped because TileServer-GL only seems to stop when I hit these particular links. Oddly enough, if I navigate to "https://144.91.**.***:444/styles/basic-preview/#0.54/0/0," it works perfectly without a hitch.

Since there are no error.log to dive into, I'm hoping someone here can help me crack this puzzle. Any insights or guidance would be much appreciated.

Thanks a ton, and let me know if you need more info to dig into this issue.

**Comment by acalcutt** [comment]
Did you install the latest c++ redistributable needed on windows? https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by acalcutt** [comment]
I tried it on server 2022 and experience the same thing. Strange. I'm guessing some dependency is missing but i'm not sure what it would be.

I have been running it fine on Windows 11 here in testing...I would imagine that is pretty similar.

**Comment by acalcutt** [comment]
After some trial and error I got it to work. It looks like in my case it was not working because I didn't install vmware tools, which includes a video driver with 3d support. The default microsoft basic video driver didn't work, but the vmware driver did.

**Comment by akram-mhss** [comment]
Thank you for your assistance. The issue I'm facing is that I'm using Windows Server 2022 on RDP, and it's displaying "Microsoft Remote Display Adapter" and "Microsoft Basic Display Adapter." Now, should I download the SVGA 3D driver will work, or should I change the RDP graphics mode?

**Comment by acalcutt** [comment]
Seems to work fine over RDP, once the real video card is updated to an appropriate driver. What kind of server is this, is it a virtual server or a phsical server? Seems like you need to update the one that shows  "Microsoft Basic Display Adapter." .

For a vmware virtual server, the updated driver with 3d support come as part of the vmware tools. If this isn't a virtual server, maybe run windows update and see if it pulls in a better driver that replaces the  "Microsoft Basic Display Adapter." If this isn't vmware and windows update doesn't pull in a driver for you, you are going to need to find what video card your server uses and see if you can find a better driver for it.

![image](https://github.com/maptiler/tileserver-gl/assets/3792408/5263c8b7-3bd9-47ce-ab6b-e5e3ba8a6a74)

**Comment by acalcutt** [comment]
If you can't find a better driver, it may be possible to use Mesa3d software rendering. I have not tested this with tileserver-gl,  but I know we have used it when building maplibre-native in the github workflows, which does not have a real video card https://github.com/maplibre/maplibre-native/blob/main/.github/workflows/node-ci.yml#L262-L271 . 

I would try the driver first, since there should be one you can use in most cases, but mesa3d could be an option if it id not. we would have to reseach how to do it, but it should mostly be extracting the dlls and possibly setting and environment variable like that step in the workflow does.

**Comment by acalcutt** [comment]
To use the Mesa3d software rendering you can try this.

1.) Download https://github.com/pal1000/mesa-dist-win/releases/download/22.3.5/mesa3d-22.3.5-release-msvc.7z
2.) extract the files 'opengl32.dll', 'libgallium_wgl.dll', 'libGLESv2.dll', 'libglapi.dll' into the maplibre-native lib folder at \node_modules\@maplibre\maplibre-gl-native\lib\node-(your node version)\
3.) set the windows environment variables. I set them in user variables, but system variables should also work
```
LIBGL_ALWAYS_SOFTWARE: true
GALLIUM_DRIVER: softpipe
```
4.) Make sure to restart your command prompt to get the new environment variables.
5.) Try to run "node ." and see if the page loads now.

![image](https://github.com/maptiler/tileserver-gl/assets/3792408/1e86bd5a-1788-488b-9ab1-bceda168a6a5)

**Comment by akram-mhss** [comment]
ok I will give this a try, and I'll get back to you with the results tnx sir

**Comment by akram-mhss** [comment]
It worked perfectly; thank you so much for your assistance

**Comment by acalcutt** [comment]
Glad you got it working. did you go the fixing the driver route or the mesa3d software rendering route? If it is possible the upgrading the driver route is the better way to go, but at least there is an option.

**Comment by akram-mhss** [comment]
I followed your instructions and used the mesa3d software, and it's working perfectly.

**Comment by acalcutt** [comment]
v4.7.0 should actually work on windows without any tweaks

**Comment by akram-mhss** [comment]
Hello,

I am encountering an issue while trying to run tileserver-gl on a server without internet access. I have successfully set up tileserver-gl on other servers using a prepared folder with all necessary files, but on this particular server, I receive the following error:

`C:\Users\andreas\Desktop\map> npx tileserver-gl --mbtiles africa.mbtiles

node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
Error: Le module spécifié est introuvable.
\\?\C:\Users\andreas\Desktop\map\node_modules\@maplibre-gl-native\lib\node-v108\mbgl.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/helpers:107:18)
    at require (node:internal/modules/cjs/helpers:132:18)
    at Object.<anonymous> (C:\Users\andreas\Desktop\map\node_modules\@maplibre-gl-native\platform\node\index.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Node.js v18.18.1`

**Comment by acalcutt** [comment]
Closed by https://github.com/maptiler/tileserver-gl/issues/1308#issuecomment-2217883101
