### ISSUE TITLE
style.json broken in 4.6.0

### ISSUE THREAD

**Issue by ryan-shaw** [maptiler/tileserver-gl#1022]
Hi, in https://github.com/maptiler/tileserver-gl/blob/master/src/server.js#L540

the code has changed from

```
style.id = id;
style.name = (serving.styles[id] || serving.rendered[id]).name;
style.serving_data = serving.styles[id];
style.serving_rendered = serving.rendered[id];
```

to

```
return {
      id,
      name: (serving.styles[id] || serving.rendered[id]).name,
      serving_data: serving.styles[id],
      serving_rendered: serving.rendered[id],
      ...style,
    };
```

which means the `id` value in `style` is overriding the parms set `id`. I'm not sure if this is intentional or not but has broken our setup as the `viewer` template is now returning the wrong `id` and returning 404 for the style.json

**Comment by acalcutt** [comment]
This was not intentional and if you have the code needed to revert I would appreciate a PR and I will make a patch version.

**Comment by acalcutt** [comment]
so at the end it appends style with ...style, which overrides the id set above?

**Comment by ryan-shaw** [comment]
Yes, I'm no nodejs dev but what I can see is `id` is contained in the `style` object but does not match the `id` above and the deconstructing of the object overwrites the `id` with an incorrect value

**Comment by acalcutt** [comment]
Did it fix your issue?

**Comment by ryan-shaw** [comment]
Haven't tried yet, will let you know when I have
