### ISSUE TITLE
4.5.2-4.6.1 breaks URL-based "glyphs" and "sprites" (concats URLs with root paths?)

### ISSUE THREAD

**Issue by alex-kowalczyk** [maptiler/tileserver-gl#1025]
With the following config.json and mystyle.json (relevant fragments) 4.5.1 displays nice map,
while after updated to 4.6.0 it emits errors for glyphs and fonts and does not display vector map at all. Moreover, errors indicate that sprites URLs are concated with local "/data" root prefix. 
Revert to 4.5.1 fixed the issue.

Errors on startup:
```
mlgl: {
    class: 'Style',
    severity: 'ERROR',
    text: "Failed to load sprite: ENOENT: no such file or directory, open '/data/https://static.mydomain.eu/sprites/osm-liberty-topo@2x.json'"
}
```
Errors when serving:
```
ERROR: Trying to use Arial Unicode MS Regular as a fallback
ERROR: Font not found: Roboto Condensed Italic
ERROR: Trying to use Arial Unicode MS Regular as a fallback
ERROR: Font not found: Arial Unicode MS Regular
GET /fonts/Roboto%20Condensed%20Italic/0-255.pbf 400 41 - 4.819 ms
ERROR: Font not found: Arial Unicode MS Regular
```

config.json:
```json
{
  "options": {
    "paths": {
      "root": "/data",
      "styles": "styles",
      "fonts": "",
      "sprites": "",
      "mbtiles": ""
    },
    "domains": [
      "my.domain"
    ],
    "serveAllFonts": false,
    "serveStaticMaps": false
  },
  "styles": {
    "mystyle": {
      "style": "mystyle.json",
      "tilejson": {
        "type": "overlay",
        "bounds": [12.08477,48.54292,18.86321,51.06426]
      }
    }
  },
  "sources": {
     "europe": {
        "url": "mbtiles://{europe}",
        "type": "vector"
     }
  },
  "data": {
    "europe": {
      "mbtiles": "tiles.mbtiles"
    }
  }
}

```

mystyle.json:
```
{
  "version": 8,
  "name": "MyStyle",
  "center": [18.4803, 54.46639],
  "zoom": 13,
  "sources": {
    "mystyle": {
      "type": "vector",
      "url": "mbtiles://tiles.mbtiles"
    },
  },
  "id": "mystyle"
  "sprite": "https://static.mydomain.eu/sprites/osm-liberty-topo",
  "glyphs": "https://fonts.mydomain.eu/{fontstack}/{range}.pbf",
  "layers": [...]
}
```

**Comment by acalcutt** [comment]
have you tried if v4.6.1 fixes it?

**Comment by acalcutt** [comment]
I just tested your style and it looks like it is the same in 4.6.1 . I didn't change anything specific to glyphs and sprites, so I will have to try and track it down.

**Comment by alex-kowalczyk** [comment]
@acalcutt thanks for your response. Looking at the changelog, this 4.5.2 change might be related:
"chore: cleanup useless decodeURIComponent() calls" 
https://github.com/maptiler/tileserver-gl/pull/1002/files

**Comment by acalcutt** [comment]
I does seem like
https://github.com/liberty-rider/tileserver-gl/blob/869ab0489cb7b5396b46c051deda6afd15f38808/src/serve_rendered.js#L26
partially causes the issue.

With that included the style json returns
![image](https://github.com/maptiler/tileserver-gl/assets/3792408/fe232ae9-32f1-441e-9976-955e0a0c535f)

But with the old tester string it returns
![image](https://github.com/maptiler/tileserver-gl/assets/3792408/2bf69f6e-5da3-406c-918d-21edf48bc164)


I do have to wonder though, did raster maps work at all for you before with this style? There is also this other code on the rendering side that always seems to append path
https://github.com/maptiler/tileserver-gl/blob/master/src/serve_rendered.js#L1237-L1260
which seems like it would have broken rendering for this style, and that has been like that for a while

**Comment by alex-kowalczyk** [comment]
I used vector tiles only. Do you mean server-side rendered rasters of my vectors?
Just tried to access "raster" variant on 4.5.1 through tileserver UI and yes, they work fine (fonts and glyphs correctly rendered on them)

**Comment by acalcutt** [comment]
I missed that the http testing code was actually in two places

https://github.com/liberty-rider/tileserver-gl/blob/869ab0489cb7b5396b46c051deda6afd15f38808/src/serve_style.js#L12
https://github.com/liberty-rider/tileserver-gl/blob/869ab0489cb7b5396b46c051deda6afd15f38808/src/serve_rendered.js#L26

Any chance you can put in a PR to revert these back to 
`const httpTester = /^(http(s)?:)?\/\//;`

it will be easier for me to approve the change if someone else puts it in.

**Comment by alex-kowalczyk** [comment]
Thanks! Will do the PR.

**Comment by acalcutt** [comment]
@Caerbannog , just an fyi. this broke in v4.5.2 with https://github.com/maptiler/tileserver-gl/pull/1002

**Comment by alex-kowalczyk** [comment]
@acalcutt here goes the PR.

**Comment by acalcutt** [comment]
Thanks for the PR. I'll merge it as soon at the tests finish and make a new release.

Just a side FYI, I don't think this sections in your config.json does anything.
```
  "sources": {
     "europe": {
        "url": "mbtiles://{europe}",
        "type": "vector"
     }
  },
```
that format would be used in your style, the mystyle.json to reference (data -> europe)

**Comment by Caerbannog** [comment]
Ouch, sorry for creating this bug. I ignored the `^` in the regex when I reasoned about it.

**Comment by acalcutt** [comment]
v4.6.2 has been released, so let me know if that fixes your issue.

@Caerbannog I was just glad it wasn't my PR this time...haha

**Comment by alex-kowalczyk** [comment]
Just grabbed 4.6.2 docker image and tested with my jsons. Perfetto!
Thank you so much @acalcutt !
