### ISSUE TITLE
Tileserver crashes/throws error in tile mode for certain pbf

### ISSUE THREAD

**Issue by christian2701** [maptiler/tileserver-gl#1041]
Hello everyone, we are currently working on a conversion of our stack to Maplibre and would also like to provide the raster tiles via Tileserver.

Unfortunately, there is sometimes a server crash on islands/areas near water at certain zoom levels.

Here is an example in the Venice area for 15/17506/11729.webp. For test purposes I have coloured the corresponding water area yellow:

![11729](https://github.com/maptiler/tileserver-gl/assets/48522137/44ab755a-7220-4477-9551-de34a0e840a4)

At "raster" zoom level 14 the data is drawn in correctly:

![correct](https://github.com/maptiler/tileserver-gl/assets/48522137/2e1bafca-c891-472e-b8d3-d17b792079c9)

I also have attached the corresponding PBF (please remove .txt at the end):

[5864.pbf.txt](https://github.com/maptiler/tileserver-gl/files/13214166/5864.pbf.txt)

From my point of view the geometry looks correct and there shouldn't be a water polygon.

Unfortunately, this error also occurs in Key Largo or Copenhagen. I suspect a problem with the water polygon, according to our tests in version 4.4.1 there is no crash of the server but still the mentioned issue.

Do you have any ideas or suggestions for analysing the problem in more detail? Thank you very much!

**Comment by acalcutt** [comment]
Could you provide an example mbtiles file and style?

Also, are you using webp? i though support for that was broken right now....does webp work?

**Comment by christian2701** [comment]
Thank your for your fast feedback. 

In the meantime, I have been able to narrow down the problem to the water areas. These are generated as follows:

```lua
function process_water_polygons(way, way_area)
	local waterway = way:Find("waterway")
	local natural = way:Find("natural")
	local water = way:Find("water")
	local landuse = way:Find("landuse")
	local mz = inf_zoom
	local kind = ""
	local is_river = (natural == "water" and water == "river") or waterway == "riverbank"
	if landuse == "reservoir" or landuse == "basin" or (natural == "water" and not is_river) or natural == "glacier" then
		mz = math.max(4, zmin_for_area(way, 0.01, way_area))
		if mz >= 10 then
			mz = math.max(10, zmin_for_area(way, 0.1, way_area))
		end
		if landuse == "reservoir" or landuse == "basin" then
			kind = landuse
		elseif natural == "water" or natural == "glacier" then
			kind = natural
		end
	elseif is_river or waterway == "dock" or waterway == "canal" then
		mz = math.max(4, zmin_for_area(way, 0.1, way_area))
		kind = waterway
		if kind == "" then
			kind = water
		end
	end
	if mz < inf_zoom then
		local way_area = way_area
		way:Layer("water_polygons", true)
		way:MinZoom(mz)
		way:Attribute("kind", kind)
		way:AttributeNumeric("way_area", way_area)
		way:ZOrder(way_area)
		if way:Holds("name") then
			way:LayerAsCentroid("water_polygons_labels")
			-- way:MinZoom(13)
			way:MinZoom(10)
			way:Attribute("kind", kind)
			way:AttributeNumeric("way_area", way_area)
			way:ZOrder(way_area)
			setNameAttributes(way)
		end
	end
end
```

The corresponding style for this layer:
````json
{
  "id": "water-area",
  "type": "fill",
  "source": "smartmaps",
  "source-layer": "water_polygons",
  "minzoom": 12,
  "filter": [
    "all",
    ["==", "kind", "water"]
  ],
  "layout": {"visibility": "visible"},
  "paint": {
    "fill-color": "#a2c1f7",
    "fill-opacity": 1
  }
}
´´´´

I have noticed that the water geometries created here sometimes look strange. Besides the actual geometry, a "border" is created around the geometry:
![wrong_geometry](https://github.com/maptiler/tileserver-gl/assets/48522137/868bd500-15b1-41e5-9bb7-99802c52edbc)

Im Vergleich sieht die Geometrie in OpenMapTiles wie folgt aus
![omt_correct_geometry](https://github.com/maptiler/tileserver-gl/assets/48522137/812d1e77-4f6e-4155-b29e-ce64c902ced2)

Any attempts with highres, lowres tiles or without simplify or combine have not led to any improvement. I am now very sure that the issue occurs with these geometries only, without water layers Venice is drawn in correctly.

**Comment by acalcutt** [comment]
Testing with your [it-nord-est-latest-wateronly-lowres.mbtiles](https://github.com/maptiler/tileserver-gl/files/13236898/it-nord-est-latest-wateronly-lowres.mbtiles.txt) and water style I was not able to get any crash to happen.

In raster mode I do see what you are talking about. It looks like the water layer takes over full tiles sometimes...
You can see it completely blocks out land at some zooms
![image](https://github.com/maptiler/tileserver-gl/assets/3792408/306868e2-5176-454a-ab9b-0c962ca4fefd)
and at zoom 15 the water seems to take over a whole tile
![image](https://github.com/maptiler/tileserver-gl/assets/3792408/2ef80505-64d1-4312-8f7f-12c61d9e66e4)

not sure what the solution is though... in inspect the data looks fine to me.

it may be worth testing if we can get this to happen in maplibre-native like i mentioned in the other thread, since this seems more like a rendering issue.

**Comment by christian2701** [comment]
Thanks again @acalcutt! The issue was caused by tilemaker and was fixed a couple of minutes ago: https://github.com/systemed/tilemaker/issues/574

**Comment by acalcutt** [comment]
Glad to hear it is working 👍
