### ISSUE TITLE
broken docker image maptiler/tileserver-gl-light:v4.6.3

### ISSUE THREAD

**Issue by albanm** [maptiler/tileserver-gl#1042]
It is missing the node exec and node_modules directory at least.

```
$ docker run -it --rm maptiler/tileserver-gl-light:v4.6.3
/usr/src/app/docker-entrypoint.sh: 4: exec: node: not found
```

**Comment by albanm** [comment]
The [Dockerfile](https://github.com/maptiler/tileserver-gl/blob/master/Dockerfile_light) is missing `apt-get install -y nodejs;`.

Also the `npm ci` instruction is ran inside a series of commands separated by ";" instead of "&", which probably explains why it failed but did not break the image build.

**Comment by acalcutt** [comment]
I didn't realize i broke this when i was troubleshooting why the npm ci was failing on arm.

If you want to submit a PR to fix this it will help me approve it easier.

**Comment by albanm** [comment]
Sure, I will prepare a PR.

**Comment by albanm** [comment]
Is it on purpose that Dockerfile_light references docker-entrypoint.sh and not docker-entrypoint_light.sh ?

**Comment by acalcutt** [comment]
Nevermind, I just fixed is manually, so a pr should not be needed unless  you think more changes should be made.

And yes, the name is on purpose. when the publish.js script copies files it renames this file
https://github.com/maptiler/tileserver-gl/blob/master/publish.js#L51

**Comment by albanm** [comment]
Ok, thanks !

**Comment by acalcutt** [comment]
v4.6.5 light version should be fixed
