### ISSUE TITLE
Crashing tileserver-gl worker (docker, kernel trap)

### ISSUE THREAD

**Issue by okimiko** [maptiler/tileserver-gl#1046]
Our tileserver is crashing over time with a kernel trap, the process itself exits with the following message:
`terminate called without an active exception`

But dmsg states the following (each error is a crash):
```
traps: Worker 2[2650] general protection ip:7f9e51a69941 sp:7f9bb1d3c6a0 error:0 in libc-2.31.so[7f9e51a69000+178000]
traps: Worker 1[5572] general protection ip:7f7084681941 sp:7f706958c6a0 error:0 in libc-2.31.so[7f7084681000+178000]
traps: Worker 4[7776] general protection ip:7efc223e5941 sp:7ef98153b6a0 error:0 in libc-2.31.so[7efc223e5000+178000]
```

We use the docker image maptiler/tileserver-gl in the latest version v4.6.5 (previously v4.4.10, which caused the same error, but I have no logs for that) deployed as swarm service. We have clients, which use vector and raster mode. 
Our first assumption was, that the services crashes, when under heavier load (major city hopping with deep zoom), but it seems, that there is no prove for that: The service is crashing even after a few requests.

Underlying operating system is CentOS 7.9 with docker 20.10.9. We use planet mbtiles generated by openmaptiles with a slightly modified osm-liberty style. The tileserver-gl runs behind nginx with caching enabled.

I appreciate any help, please ask, if I can provide more details/logs.

**Comment by acalcutt** [comment]
can you share a mbtiles file and style that has yhe issue you are describing?

**Comment by okimiko** [comment]
I'm using a planet file generated of a planet file from 29.09.2023  with openmaptiles 3.14.0 including a PR for power layer support (https://github.com/openmaptiles/openmaptiles/pull/1235).

I got another log from today, which may indicate, that the issue is related to the raster context (and uses the default basic-preview):

```
2023-11-09T07:56:02.982470975Z Starting tileserver-gl v4.6.5
2023-11-09T07:56:02.983372184Z Using specified config file from /data/config.json
2023-11-09T07:56:02.984469550Z Starting server
2023-11-09T07:56:03.546813357Z Listening at http://[::]:8080/
2023-11-09T07:56:05.093829578Z Startup complete
2023-11-09T07:56:32.150059691Z GET /health 200 2 - 7.654 ms
2023-11-09T07:57:02.287725708Z GET /health 200 2 - 1.313 ms
2023-11-09T07:57:32.431165638Z GET /health 200 2 - 0.905 ms
2023-11-09T07:57:59.422424207Z GET /styles/basic-preview/4/8/7.png 200 36017 - 814.085 ms
2023-11-09T07:57:59.424130102Z GET /styles/basic-preview/4/7/7.png 200 26364 - 647.433 ms
2023-11-09T07:57:59.425352375Z GET /styles/basic-preview/4/4/7.png 200 29468 - 647.778 ms
2023-11-09T07:57:59.459297553Z GET /styles/basic-preview/4/4/4.png 200 8821 - 681.490 ms
2023-11-09T07:57:59.462920254Z GET /styles/basic-preview/4/5/6.png 200 3200 - 684.008 ms
2023-11-09T07:57:59.558214839Z GET /styles/basic-preview/4/9/7.png 200 36017 - 776.967 ms
2023-11-09T07:57:59.608850708Z GET /styles/basic-preview/5/15/10.png 200 30920 - 142.498 ms
2023-11-09T07:57:59.682317153Z GET /styles/basic-preview/5/20/11.png 200 20338 - 212.637 ms
2023-11-09T07:57:59.682335928Z GET /styles/basic-preview/5/14/11.png 200 1833 - 212.530 ms
2023-11-09T07:57:59.751249979Z GET /styles/basic-preview/5/19/9.png 200 23560 - 283.894 ms
2023-11-09T07:57:59.753650473Z GET /styles/basic-preview/5/14/12.png 200 2690 - 288.144 ms
2023-11-09T07:57:59.757806761Z GET /styles/basic-preview/5/19/12.png 200 39529 - 292.546 ms
2023-11-09T07:57:59.786706287Z GET /styles/basic-preview/5/16/9.png 200 21040 - 29.973 ms
2023-11-09T07:57:59.806105253Z GET /styles/basic-preview/5/14/10.png 200 1833 - 49.651 ms
2023-11-09T07:57:59.878686962Z GET /styles/basic-preview/5/17/9.png 200 29598 - 73.551 ms
2023-11-09T07:57:59.890817413Z terminate called without an active exception
```

Related kernel log:
```
Nov 09 07:57:59 hostname kernel: traps: Worker 3[25497] general protection ip:7f0605611941 sp:7f03654126a0 error:0 in libc-2.31.so[7f0605611000+178000]
```

Anyway, I will publish my fork of osm-liberty later (most changes are formatting, thanks to jq -.-).

On the other side I have a pmtile generated with planetiler 0.7 and some customisations (power, trees and MIN_PIXEL_SIZE_THRESHOLDS fix). I will switch to this file on the test server.

PS: @acalcutt - Thanks for adding pmtile support in the latest release and remember me to check out planetiler! :)

**Comment by acalcutt** [comment]
That crash error does look very c++ related, so this being a maplibre-native crash could make sense. I've seen something similar in https://github.com/maplibre/maplibre-native/issues/574 where an exception thrown by maplibre-native killed tileserver with some type of libc error.

**Comment by okimiko** [comment]
Yes, it should be C++ related; error:0 indicates division by zero as far as I googled ... Is it possible to enable some kind of debug messages for maplibre-native?
I think I recognized the other bug (or better the resulting MLGL error messages) earlier, it would be nice to get the same behaviour for any crash (if the assumption that maplibre-native is causing it, is correct).

Short/early update:
Since switching to pmtiles the server is running about 7h. I think, that we have the same usage as we have the last days. May be it works for now.
I will check my previous openmaptiles mbtile release (from march without power layer) next week (because AFAIK we had no issues with this one). At least to verify that it is data related.

**Comment by acalcutt** [comment]
On a unrelated side note, if you end up using 3d terrain with your planetiler 0.7 file, i just submitted this bug with buildings https://github.com/maplibre/maplibre-gl-js/issues/3313

**Comment by okimiko** [comment]
> On a unrelated side note, if you end up using 3d terrain with your planetiler 0.7 file, i just submitted this bug with buildings [maplibre/maplibre-gl-js#3313](https://github.com/maplibre/maplibre-gl-js/issues/3313)

Thanks for the hint, but we mostly use 2d maps. 

Netherheless I just checked a style with 3d buildings (is that meant with 3d terrain or is this something different?) and cannot confirm the problem except the multi-polygon buildings in the data:
![grafik](https://github.com/maptiler/tileserver-gl/assets/39791814/ce829cc5-5462-4444-ba63-b0118a31e8b9)
![grafik](https://github.com/maptiler/tileserver-gl/assets/39791814/863d98d9-6069-4d6c-8647-0d78b7022e90)

**Comment by acalcutt** [comment]
its is only when 3d terrain is enabled that there is an issue with floating buildings. it should be fine without terrain. just wanted to bring it up incase you saw some floating buildings :-)

**Comment by okimiko** [comment]
Okay, your hint was even bigger than thougt; I just found out that there is something like terrain RGB, the last thing I checked out were rastered contours, but not this /o\

Thanks again ;-)

**Comment by okimiko** [comment]
> Short/early update: Since switching to pmtiles the server is running about 7h. I think, that we have the same usage as we have the last days. May be it works for now. I will check my previous openmaptiles mbtile release (from march without power layer) next week (because AFAIK we had no issues with this one). At least to verify that it is data related.

Still no more crashes, so I am convinced, that it is related to the underlying tiles and probably a not optimal handling of what ever data causes the crash. I will test my previous openmaptiles mbtiles next week, may be I find something in a flle, which has a uploadable size.

**Comment by Caerbannog** [comment]
Maybe

**Comment by okimiko** [comment]
And again: No more crashes, I could not reproduce the error with a small mbtile (planet 0-7), so I will close this issue here. If I stumble over an issue like this again, I will open an issue at maplibre/maplibre-native.

@acalcutt: Thanks for your work and support!
