### ISSUE TITLE
Texts are cut off in raster maps and static maps

### ISSUE THREAD

**Issue by tonsnoei** [maptiler/tileserver-gl#1114]
I am running v4.4 of Tileserver GL with a map of the Netherlands. Currently I have the problem that texts on the maps are cut off in several places. It looks ugly and I'd like to solve but don't know how. Can somebody help me out? 

![example1](https://github.com/maptiler/tileserver-gl/assets/8810118/68fed063-4c0d-42bb-9e2a-91faba611d06)
![example2](https://github.com/maptiler/tileserver-gl/assets/8810118/95c952f9-fb01-4779-a222-2cfb1e2b3a8c)

**Comment by candux** [comment]
You have to set the tileMargin Option in your config. This reduces Problems like this in raster-maps but will also decrease performance.
See https://maptiler-tileserver.readthedocs.io/en/latest/config.html#tilemargin

**Comment by tonsnoei** [comment]
Thanks! I set the value to 1. This helps me out. But I cannot find in the documentation what kind of unit tile margin is. Can it be a value with decimal places and does 1 mean a single tile? What is a correct value to use?

**Comment by acalcutt** [comment]
I don't have a specific value for you, but I have used 10-20 in testing. Think if that value as how many pixels will be added around each tile. So our normal tiles are 256x256, if you add a tile tile margin of 10, i think that makes the image 276x276. You want to keep this value as low as possible, while getting it high enough to fix the label clipping.  You could go really high if you wanted, but it makes the images bigger and longer to load, so you want a good balance.

Adding the extra margin allows the renderer to take into consideration labels that may start in the next tile over, so it has to be a big enough see the labels in the next tiles so it can render them.

**Comment by acalcutt** [comment]
Good to hear. I am supprised that is enough, but if it works that's great.

I'm going to close this
