### ISSUE TITLE
Question about cache. Fast loading of tiles.

### ISSUE THREAD

**Issue by EgorSaffrezzi** [maptiler/tileserver-gl#1138]
I'm not sure that the question relates specifically to the cache, but the behavior that I want to implement should greatly speed up the loading of tiles.

I have a map, and my tile server that generates raster tiles for me on the fly, can I somehow run the map and save the tiles themselves as pictures in a folder, so that when a person uses it, the tiles are returned to him instantly from the folder.

Here's an example:

No matter how fast I move the map, the tiles load instantly....

https://www.mapiful.com/editor/#/editor/location

<img width="1468" alt="image" src="https://github.com/maptiler/tileserver-gl/assets/82441920/332242fe-9826-491e-9eba-6ab409597b06">

**Comment by acalcutt** [comment]
Typically to do caching, people put something like cloudflare or nginx caching, like mentioned in https://maptiler-tileserver.readthedocs.io/en/latest/deployment.html#caching
