### ISSUE TITLE
MBtiles data with static png images lead to erroneous URLs in index.json

### ISSUE THREAD

**Issue by Adrien-Atmosphere** [maptiler/tileserver-gl#1159]
Hello, 

I am using tileserver-gl with docker. The problem appeared with the introduction of  tileSize in the URLs.
Version working as expected : 4.8.0
Version not working anymore : 4.9.1 and 4.10.0

Problem description: 
I am using pre-rendered static png images in a MBtiles archive. The working URL format to fetch the tiles is "http://127.0.0.1:8888/data/basic/{z}/{x}/{y}.png". 
But when I request "http://127.0.0.1:8888/index.json", it gives me a URL for the tiles which is "http://127.0.0.1:8888/data/basic/256/{z}/{x}/{y}.png". Here the 256 is definitely the tileSize parameter which was introduced recently. 

Expected behavior: 
Having URLs in index.json that match the working URLs.

**Comment by acalcutt** [comment]
This is a bug since the data endpoints are not supposed to have a TileSize in them. I've made an update to fix this in https://github.com/maptiler/tileserver-gl/pull/1160 , but I still have to update documentation to match this update.

**Comment by Adrien-Atmosphere** [comment]
Thank you! I just downloaded the latest docker image and it works properly.
