### ISSUE TITLE
Unhandled exception when pmtiles is used and GeoJSON is requested

### ISSUE THREAD

**Issue by Jollyfant** [maptiler/tileserver-gl#1187]
In `serve_data.js` an exception is triggered because `isGzipped` is undefined: https://github.com/maptiler/tileserver-gl/blob/master/src/serve_data.js#L73 when `pmtiles` is used as data source and GeoJSON is requested.

Solution is to either add a check for Gzip magic bytes as per https://github.com/maptiler/tileserver-gl/blob/master/src/serve_data.js#L120 or remove the check entirely.

**Comment by acalcutt** [comment]
Just wondering, do you have an example pmtiles geojson file I can test with? The PR looks good, I just realized geojson pmtiles isn't something I have tested before.

**Comment by acalcutt** [comment]
Nevermind, I forgot this isn't a geojson formatted pmtiles, but a pbf pmtiles in geojson format. I can test with what I have.

**Comment by acalcutt** [comment]
Thank for the PR, it has been merged. I will try to make a new release when I get home later tonight.

**Comment by acalcutt** [comment]
Fixed by https://github.com/maptiler/tileserver-gl/pull/1188
