### ISSUE TITLE
Raster tiles file recognized as vector tiles

### ISSUE THREAD

**Issue by veitbjarsch** [maptiler/tileserver-gl#1258]
I've set up a tile server and created a mbtiles file which contains raster tiles. But when I reference the file inside the data prop, it states that the containing files are vector-file. 

I could not find any documentation how to manually address this issue. So it might be a bug or do I missing something?

- tileserver-gl v4.11.1
- CentOS 7

![image](https://github.com/maptiler/tileserver-gl/assets/12811012/dfab01ef-8c86-4db6-a75c-b750b0d5a284)

config.json
```{
    "options": {
        "paths": {
            "root": "/data",
            "mbtiles": "/data"
        },
        "maxScaleFactor": 3,
        "maxSize": 2048,
        "pbfAlias": "pbf",
        "serveAllFonts": false,
        "serveAllStyles": false,
        "serveStaticMaps": true,
        "tileMargin": 0
    },
    "styles": {
        "snow": {
            "style": "style.json",
            "tilejson": {
                "bounds": [
                    -180,
                    -85.0511,
                    180,
                    85.0511
                ]
            }
        }
    },
    "sources": {
        "snow": {
            "url": "mbtiles://snow.raster.mbtiles",
            "type": "raster"
        }
    },
    "data": {
        "snow": {
            "mbtiles": "snow.raster.mbtiles",
             "type": "raster"
        }
    }
}
```

**Comment by acalcutt** [comment]
My guess would be your mbtiles file is missing format in the metadata table. I am pretty sure if format is not specified it defaults to pbf. You can check this with a sqlite editor, like
```
# sqlite3 jaxa_color.mbtiles
sqlite> select * from metadata where name='format';
format|png
```
I assume the last line returns nothing in your case, in which case you can add it in with something like
`INSERT INTO metadata (name,value) VALUES('format','png');`
(where 'png' is should be your real image type)

**Comment by acalcutt** [comment]
As far as i can see from he documentation there is no way to change the format of a data file other than editing the file. You could likely still make a style and specify the data as a raster and it would probably work, despite showing wrong under data. but to fix it I think you need to do the sqlite commands I mentioned.

**Comment by veitbjarsch** [comment]
@acalcutt thanks for the help. This was indeed the problem.
