### ISSUE TITLE
Map Fonts: 400 Bad Request

### ISSUE THREAD

**Issue by vzkharov** [maptiler/tileserver-gl#1268]
Locally all works great, even `Roboto` fonts are got.

Local Machine:
- System: Apple Silicon M2

But on Hetzner Server when fonts are requested — `400 Bad Request`

Production Setup:
- System: Ubuntu 20.4 LTS
- Logs:

```sh
GET /data/planet/3/4/3.pbf 200 439858 - 19.311 ms
GET /data/planet/4/8/4.pbf 200 175999 - 11.599 ms
GET /data/planet/4/8/5.pbf 200 375107 - 17.883 ms
GET /data/planet/4/9/4.pbf 200 193329 - 25.560 ms
GET /data/planet/4/9/5.pbf 200 314155 - 41.204 ms
GET /data/planet/4/9/6.pbf 200 345074 - 41.865 ms
GET /data/planet/4/8/6.pbf 200 303923 - 6.839 ms
GET /fonts/Roboto-Bold/7168-7423.pbf 400 2 - 1.494 ms
GET /fonts/Roboto-Bold/1024-1279.pbf 400 2 - 3.183 ms
GET /fonts/Roboto-Bold/256-511.pbf 400 2 - 1.753 ms
GET /fonts/Roboto-Regular/8192-8447.pbf 400 2 - 6.302 ms
GET /fonts/Roboto-Regular/7168-7423.pbf 400 2 - 6.767 ms
GET /fonts/Roboto-Regular/512-767.pbf 400 2 - 7.134 ms
GET /fonts/Roboto-Regular/1024-1279.pbf 400 2 - 10.770 ms
GET /fonts/Roboto-Regular/256-511.pbf 400 2 - 6.759 ms
GET /fonts/Roboto-Bold/65024-65279.pbf 400 2 - 5.670 ms
GET /fonts/Roboto-Regular/0-255.pbf 400 2 - 5.613 ms
GET /fonts/Roboto-Bold/4864-5119.pbf 400 2 - 2.697 ms
GET /fonts/Roboto-Bold/64256-64511.pbf 400 2 - 2.657 ms
GET /fonts/Roboto-Bold/4608-4863.pbf 400 2 - 4.108 ms
GET /fonts/Roboto-Bold/768-1023.pbf 400 2 - 2.11
```

(setup)
```sh 
Starting tileserver-gl-light v4.10.3
Using specified config file from config.json
Starting server
Listening at http://[::]:3001/
Style "basic" changed, updating...
Style "brand" changed, updating...
Startup complete
GET / 200 3068 - 44.217 ms
```

Any ideas how to fix this?

**Comment by acalcutt** [comment]
@prashis So does that cause the mentioned issue? seems strange it would work in on place and not the other. It looks like to fix it we would likely have to fork [@mapbox/glyph-pbf-composite](https://github.com/mapbox/glyph-pbf-composite/blob/master/package.json#L7) or move the functions into tileserver-gl, since that package doesn't seem maintained anymore.

Just a note for the original post, as of 4.8.0, Ubuntu 22.04 is required for linux. without that maplibre-native will be missing dependencies.

**Comment by jessekrubin** [comment]
Try this (same api): https://github.com/jessekrubin/pbfont ?

I have not used tileserver-gl, but a tileserver-gl user found my lib and sent me this issue.

**Comment by prashis** [comment]
@acalcutt I've tried using https://github.com/jessekrubin/pbfont instead of `@mapbox/glyph-pbf-composite` & this issue was resolved. Could we use `@jsse/pbfont`?

**Comment by acalcutt** [comment]
Its seems like a good alternative that is more up to date.

**Comment by jessekrubin** [comment]
FWIW it works well on front end and backend. I am compositing glyphs both places. 

PS: if you're into map tiles you might like some of the tools I have made. 🔌

**Comment by steve-maptaskr** [comment]
I suspect this may be related to: https://github.com/maptiler/tileserver-gl/issues/1295

**Comment by acalcutt** [comment]
Can anyone confirm v4.12.0  fixes this.

**Comment by steve-maptaskr** [comment]
I can confirm that with Node 20.15.0, and v4.12.0 the new @jsse/pbfont is function as expected, and there is no longer any issues.
Thank you all very much!

**Comment by jessekrubin** [comment]
Anytime Steve! It definitely beats having to composite  the fonts by hand w superglue.
