### ISSUE TITLE
Raster mutilang support

### ISSUE THREAD

**Issue by Marco-Kl** [maptiler/tileserver-gl#1407]
Hello community,
I have problems to render tiles with multilang support. 

I created a custom planet.mbtiles with all language tags like name:de, en, it, pl, sp.... which are available in the planet.pbf 
If I using the inspector to see all the objects everything is fine as expexted. 
I created a style with maputnik with a case statement which provides me the label in two languages with the ability to fallback i a language is not available. This works fine in the vector layer.  But is i try to get this via the raster layer, it will not work in the higher zoom level. 
If I open the raster map, the country is displayed in multilanguage, if I zoom in till the cities are showing up, then only the name:en is rendered. Same when I'm removing the case statement, name:en will be rendered , name:xx are not renderd.

I rendered a new mbtiles where the name tag is set by a preferred language. So name is like name:it. This is also ignored by the renderer. If a name:en is awailable, the renderer always prefer this. This will start at zoom which show the Cities and will always show name:en until the node has no name:en. 

I am using the latest Release v5 as docker but i have the same issue on 4.6.6
The first screenshot is the working vetor layer. 

Regards Marco 

![2024-10-28_21-19](https://github.com/user-attachments/assets/8366dea2-7dcf-43ff-a99d-0b968e95310d)
![Bildschirmfoto vom 2024-10-28 21-15-58](https://github.com/user-attachments/assets/bdefdd38-2bf9-43fe-8cc8-694dbc9dc678)
![2024-10-28_21-16](https://github.com/user-attachments/assets/1a693a17-6bbc-441d-81cd-564794457c3f)
![Bildschirmfoto vom 2024-10-28 21-15-24](https://github.com/user-attachments/assets/61db8a75-8131-402c-9ae3-33f14cf53717)
![Bildschirmfoto vom 2024-10-28 21-15-46](https://github.com/user-attachments/assets/01d0f1b8-761b-4456-8724-6c70a7478166)

**Comment by acalcutt** [comment]
Are you using maplibre native to generate the rasters? In tileserver gl, which uses maplibre native, I have seen thing like this when the fonts you are using dont include the symbol. For example, with chinese characters https://github.com/maptiler/tileserver-gl/issues/621

I believe maplibre-js would work because it can use browser fonts, but native has no fallback and needs the right fonts supplied

**Comment by Marco-Kl** [comment]
Hi acalcutt,
thanks for your faste response. I confusing me a little bit, because japanese is redered in a lower zoom, but i think you pushed me into the right direction. It must be something with the font. Maybe a scale problem. 
You can also see the font is rendered in a very high zoom, but not for city, town, village etc. (screenshot #1) . Only water objects. 
If i replacing case statement with japan only, it will still not rendered for those kind of place. I will try to play a liitle bit with the style....maybe there is a collision at rendering. 
Ideas are welcome to get a little bit more output for debugging. 

I replaced the "ja" tag with "fr" and both are rendered (screnshot #2)
![2024-10-29_07-29](https://github.com/user-attachments/assets/a78d0eb3-901c-4fad-ab56-da0d05fe2627)
![Uploading Bildschirmfoto vom 2024-10-29 07-29-24.png…]()

**Comment by Marco-Kl** [comment]
Hi acalcutt,
it was the right hint from your side. But is was not the renderer, it was a broken Noto Font. I replaced the whole font folder an its works in that second. 

Thank you very much

![image](https://github.com/user-attachments/assets/0edac817-c1e6-4cf9-ae66-295c116649d3)

**Comment by Marco-Kl** [comment]
Solved.
