### ISSUE TITLE
Cannot configure png images at 256x256@96dpi

### ISSUE THREAD

**Issue by BHudsonJSI** [maptiler/tileserver-gl#174]
Developers of code that use tiles from the tile server have requested png tiles at 256x256@96dpi.  The tile server only seems to generate images at 25.4dpi.  

I have tried several combinations of maxsize and maxscalefactor but am unable to get images that match this requirement.  

Is there some configuration change that I can make to get the output images to match this spec?

**Comment by BHudsonJSI** [comment]
Devs changed their code to support the tile sizes provided by tileserver-gl.  It would still be nice to have some choices in rendered image sizes dpi.

**Comment by petrsloup** [comment]
What configuration are you using and what URLs are you requesting from the server?

The server currently supports `maxScaleFactor` up to `9`.

Also note that the `dpi` unit does not represent any specific value here -- the server only works with pixel dimensions, which are not directly "convertable" to dpi -- it all depends on the physical dimensions that you "assign" to the image when printing (for example).

So, you mentioned `256x256@96dpi` -- what pixel dimensions are you expecting in this case?

**Comment by BHudsonJSI** [comment]
At this time I am using the defaults.  My specified quality config looks like this (not currently specifying scale or size);

    "formatQuality": {
      "jpeg": 75,
      "webp": 75,
      "pngQuantization": false,
      "png": 98
    },
    "pbfAlias": "pbf",
    "serveAllFonts": false,
    "serveStaticMaps": true
  },

Using this config, any tile@2x.png results in 256x256@25.4dpi.  Getting the same tile from arcgis online gives me 256x256@96dpi.  I just wanted to be able to replicate the format of the tiles to match.

**Comment by petrsloup** [comment]
There is really no hidden magic in the server logic:
- `256x256` tile is 256x256 px
- `256x256@2x` is 512x512
- `256x256@3x` is 768x768
- `256x256@4x` is 1024x1024

You can enable ratio up to `@9x` with `"maxScaleFactor": 9` option.

What resolution (in pixels) do you expect? You can always use the static maps endpoints to get precisely the image sizes you need.

**Comment by BHudsonJSI** [comment]
I have no issue with the tile size, 256x256 is exactly what I need.

The DPI/PPI of the image that comes back is the issue.  The images come back at 25.4dpi, when what I was looking for was 96dpi.  e.g. If you are creating the image with ImageMagick you would specify a density value of 96.

**Comment by mmuelder** [comment]
A digital image does not have "dpi". The **i** stands for inch, so it's all about the physical object that you view the image on (screen, printed page).

**Comment by EgorSaffrezzi** [comment]
@petrsloup #1134 Hi. Could you help me with @ suffix ? Please.
