### ISSUE TITLE
Remove bundled styles and fonts

### ISSUE THREAD

**Issue by petrsloup** [maptiler/tileserver-gl#271]
In the next major release (v3), the bundled styles and fonts will be removed.

The current version of TileServer GL (v2) contains bundled OpenMapTiles styles and fonts (via `tileserver-gl-styles package` dependency).

It is getting increasingly hard to maintain the version of the styles and its compatibility with the latest OpenMapTiles data. When there is a new version of OpenMapTiles data released, the styles bundled with TileServer GL need to be updated in order to match the version, but there is a risk of breaking compatibility with the older version of data.

As a result, there were recent reports of missing labels (#260, #267) and possibly other issues related to this.

When the bundled styles and fonts are removed, the developers will have to download the styles (see e.g. https://openmaptiles.org/styles/) and create a `config.json` file (see http://tileserver.readthedocs.io/en/latest/config.html). Then, you will be able to upgrade the TileServer GL without worrying about unwanted style update and also update the styles independently without having to upgrade the TileServer GL.

This cleanup will also make the TileServer GL a little more data-agnostic, independent and less interconnected with the OpenMapTiles project.

**Comment by Namec** [comment]
you say V3 !!! can't wait to see what awesomness it will bring us :-)

with the current V2 version, can i solve this missing labels issue, or do i need to wait for the next version.

**Comment by petrsloup** [comment]
Yes, of course, you can solve this now -- just make sure to download the correct version of OpenMapTiles style for the OpenMapTiles data you have downloaded. The latest version of styles (see e.g. https://github.com/openmaptiles/klokantech-basic-gl-style/releases) should always be compatible with the latest version of data. (If you have some older OpenMapTiles data, you might need an older version of the style.) Then create the config file based on the documentation linked above (also see the http://tileserver.readthedocs.io/en/latest/config.html#referencing-local-files-from-style-json section).

**Comment by spatialillusions** [comment]
Before this is done, shouldn't the styles' urls be updated so that they work locally? 
https://github.com/openmaptiles/positron-gl-style/blob/master/style.json#L27
https://github.com/openmaptiles/dark-matter-gl-style/blob/master/style.json#L27
https://github.com/openmaptiles/klokantech-basic-gl-style/blob/master/style.json#L15 
They are all using https://free.tilehosting.com/data/v3.json?key={key} at the moment, and in the same way the glyphs and fonts should be made local as well, or there should be a guide for changing the properties.

**Comment by petrsloup** [comment]
Partially done in v3.0.0
