### ISSUE TITLE
Automatically Starting Zurich mbtiles

### ISSUE THREAD

**Issue by toton6868** [maptiler/tileserver-gl#326]
I am using Tileserver-gl with docker. I have created a folder in '/opt/maps' and I am running the command like 

`sudo docker run --rm -it -v /opt/maps -p 8080:8080 klokantech/tileserver-gl:latest custom.mbtiles -c config.json --verbose`

And my config file looks like

```
{
    "options": {
        "paths": {
            "root": "",
            "fonts": "fonts",
            "sprites": "sprites",
            "styles": "styles",
            "mbtiles": "tiles"
        },
        "domains": [
            "localhost:8080",
            "127.0.0.1:8080"
        ],
        "formatQuality": {
            "jpeg": 80,
            "webp": 90
        },
        "maxScaleFactor": 3,
        "maxSize": 2048,
        "pbfAlias": "pbf",
        "serveAllFonts": true,
        "serveStaticMaps": true
    },
    "styles": {
        "basic": {
            "style": "style-local.json",
            "tilejson": {
                "type": "overlay",
                "bounds": [88.0844222351, 20.670883287, 92.6727209818, 26.4465255803]
            }
        }
    },
    "sources": {
        "custom": {
            "url": "mbtiles://custom.mbtiles",
            "type": "vector"
        }
    },
    "data": {
        "custom-vector": {
            "mbtiles": "custom.mbtiles"
        }
    }
```
I put all the files custom.mbtiles, config.json file in /opt/maps/ directoty and running the docker command from that directory. But it always downloading zurich file automatically and showing zurich maps. What should I change to show the custom.mbtiles?

**Comment by petrsloup** [comment]
Maybe just a typo? There seems to be `config.js` in the command line example you posted.. it should be `config.json`.

**Comment by toton6868** [comment]
Sorry, I was using JSON but it was a typo. Currently, I am facing another problem. If i use the following command (instead of using "opt/maps/" I used $(pwd):/data)

`sudo docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl:latest --verbose --config /opt/maps/config.json;`

The custom mbtiles is showing. I run the command from the mbtiles directory. But its not running the `config.json` file. It is creating a config file automatically. As verbose is on its showing the config.json output.

```
{
  "options": {
    "paths": {
      "root": "/usr/src/app/node_modules/tileserver-gl-styles",
      "fonts": "fonts",
      "styles": "styles",
      "mbtiles": "/data"
    }
  },
  "styles": {
    "klokantech-basic": {
      "style": "klokantech-basic/style.json",
      "tilejson": {
        "bounds": [
          87.99765,
          18.58403,
          92.69043,
          26.64677
        ]
      }
    },
    "osm-bright": {
      "style": "osm-bright/style.json",
      "tilejson": {
        "bounds": [
          87.99765,
          18.58403,
          92.69043,
          26.64677
        ]
      }
    }
  },
  "data": {
    "v3": {
      "mbtiles": "custom.mbtiles"
    }
  }
}
```

I never point out the `config.json`

**Comment by StefanBrand** [comment]
Only your `pwd` is mounted into the  `data` directory. The docker container cannot access `/opt/maps/config.json`. You must put the `config.json` somewhere, where the docker container can see it, e.g. your `pwd`. Then you can write `--config /data/config.json` because your `pwd` is the `/data` that the container sees.
