### ISSUE TITLE
limit access from other domains not working

### ISSUE THREAD

**Issue by andredoering** [maptiler/tileserver-gl#385]
Hey there, I am trying to restrict access, so that only those websites that I am allowing can include the map, so that no one else can use my tileserver than those domains.

I tried it with 
```
    "domains": [
      "localhost:9090",
      "127.0.0.1:9090"
    ],
```

but it seems to be ignored. Those parameters don't load when I start the docker container and it is still accessible from everywhere.

How can I limit the access?

**Comment by klokan** [comment]
In nginx - before tileserver.

**Comment by andredoering** [comment]
Thank you for your answer. Does it work with Apache too? How can I set that up? Is there an example somewhere?

**Comment by andredoering** [comment]
This is my Apache configuration:

```
<VirtualHost *:80>

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://localhost:9090/
    ProxyPassReverse / http://localhost:9090/

    ServerName domain.com
    ServerAlias domain.com


   # setup the proxy
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>    

</VirtualHost> 
```

**Comment by klokan** [comment]
First links from basic Google query:
- https://stackoverflow.com/questions/38130081/only-allow-users-from-specific-referrer-redirect-the-rest-htaccess
- https://stackoverflow.com/questions/714332/allow-request-coming-from-specific-ip-only
etc.

> This is the right place only for a software bug report or a new software feature request.
> ...
> The usage and installation questions belongs to https://stackoverflow.com/questions/tagged/openmaptiles
A guaranteed support and consulting from the core developers via https://openmaptiles.com/support/
