### ISSUE TITLE
version `GLIBCXX_3.4.21' not found  on debian 8

### ISSUE THREAD

**Issue by nimaansary** [maptiler/tileserver-gl#405]
OS: Debian 8
node 6.15.1
nvm 0.32.1

after i installed the TileServer-gl and try to run, i get this error:

`Starting tileserver-gl v2.5.0
Automatically creating config file for /home/user/2017-07-03_asia_iran.mbtiles
Run with --verbose to see the config file here.
module.js:604
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.21 not found (required by /home/user/.nvm/versions/node/v6.15.1/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native/lib/node-v48/mbgl.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v6.15.1/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native/platform/node/index.js:5:12)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
`

after execute `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` i got the below:
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20

**the lastest available libstdc++ version for debian 8 is 4.9, but it seems that at least libstdc++ 6.0.3 is required for resolve this problem!!!!**
I have a question: 
is there any way to run tileserver-gl  on debian 8 (except docker)???

**Comment by scara** [comment]
Hi @nimaansary,
if you don't need raster support, please try _tileserver-gl-light_ which doesn't depends on a particular glibc version.

HTH,
Matteo

**Comment by nimaansary** [comment]
unfortunatelly i need raster support. i install a debian 9 on debian 8 (using schroot) and then install tileserver-gl !!
now it works well!!!
