### ISSUE TITLE
I hope to use the latest version 3.0.0 on docker as soon as possible

### ISSUE THREAD

**Issue by 459584547** [maptiler/tileserver-gl#407]
The maptiler team is great。
Thank you very much。

**Comment by timster** [comment]
Yes please! Seems to fix several issues we're having in 2.6.0.

**Comment by nickpeihl** [comment]
To add to this, the latest release of tileserver-gl published to NPM is v2.6.0 which only supports up to Node.js v6 which is no longer supported and vulnerable to security flaws. Looks like the `master` branch supports the latest Node.js releases, but it has not been published on NPM.

**Comment by xwipeoutx** [comment]
It seems to available here now: https://hub.docker.com/r/maptiler/tileserver-gl

**Comment by 459584547** [comment]
> It seems to available here now: https://hub.docker.com/r/maptiler/tileserver-gl

yes it is ,thank you  very mach
