### ISSUE TITLE
Memory leak in mapbox-gl-native 5.0.2

### ISSUE THREAD

**Issue by vcabbage** [maptiler/tileserver-gl#418]
After building and running from master (commit 9e12ee6f) with node v10.19.0 I found that memory slowly increased over time, eventually resulting in OOM.

After narrowing down the problematic section to the mbgl render call I found https://github.com/mapbox/mapbox-gl-native/pull/15922. Applying that patch and re-building mapbox-gl-native I no longer observed the behavior. I also tried with the latest mapbox-gl-native at the time (https://github.com/mapbox/mapbox-gl-native/commit/5fcc6cf24f6fc7606cf033e3b76363d0924e273b) without the PR to rule out an already merged fix, but without the patch from the PR the leak remained.

If I understand the PR correctly it's not a memory leak in the typical sense but rather the node GC doesn't realize the heap is growing and therefore doesn't trigger a GC. 

I'm currently avoiding the issue by using tileserver-gl v2.6.0 with node v6.14.4 which doesn't appear to be affected by the issue.

**Comment by oldluke92** [comment]
This issue still exists with in release version v3.0.0

**Comment by leonardehrenfried** [comment]
@oldluke92 @vcabbage How did you go about diagnosing this problem? I'm not seeing any crashes but pegged CPU and no tiles being served.

**Comment by oldluke92** [comment]
@leonardehrenfried 
I got a deployment of tileserver-gl with 3 replicas in a kubernetes cluster with metrics-sever, prometheus and grafana deployed. I was notified about high memory ( > 2GB per pod ) usage and OOM termination of pods after upgrading tileserver-gl from version 2.6.0 to 3.0.0
I could create some comparison charts if needed.
I then upped the memory limits of the pods to 4GB. No OOM kills since then.

**Comment by vcabbage** [comment]
I have been unable to reproduce this issue now. In my case memory usage was growing seemingly without bounds on a system with 128GB of memory. I'm not sure if it was something changed with this project or my environment.

Going to go ahead and close this issue as it's no longer present as far as I can tell.
