### ISSUE TITLE
Raster tile server using png data

### ISSUE THREAD

**Issue by safe-bug** [maptiler/tileserver-gl#424]
Hello
I want to run a raster tile server using tileserver-gl but I don't see anything about it in the documentation, is using mbtiles the only supported input data?

**Comment by petrsloup** [comment]
Yes, .mbtiles is the only supported input format. (With some knowledge, it is also possible to use external `http://..../{z}/{x}/{y}.png` tiles in a map style, but nevertheless, the content always needs to be tiled.)

You can use e.g. MapTiler Desktop (https://www.maptiler.com/desktop/) to process your image into .mbtiles.
