### ISSUE TITLE
Nginx Reverse Proxy with Cache

### ISSUE THREAD

**Issue by webmap2015** [maptiler/tileserver-gl#425]
Hi, I run TileServer GL behind a proxy (Nginx Reverse Proxy with Cache). It's working good.

TileServer GL generates tiles PNG format, but, in Nginx cache folder, there is no PNG format tile.

![image](https://user-images.githubusercontent.com/10267317/76657167-40784880-6582-11ea-905b-a8a698e7e79f.png)

How can I cache in orijinal (PNG) format?

Thanks.

**Comment by oldluke92** [comment]
Hi,

This is not a Tileserver-GL Question and especially no issue.

Still, have a short response and some resources:

nginx is not saving the original filenames/paths in the filesystem structure.
It's caching algorithm generates the Filename by default based on the cache key ( default: $scheme$proxy_host$request_uri ), hashing it using MD5, and then saving it in a folder structure based on your caching settings.
By looking at the path you got, I guess that you configured your cache to use levels 1:2:2.
That way, it generates folders based on the last character of the hash, then a second level of folders based on the next 2 followed by folders based on the following

Further reading:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html (search for "levels" and "cache-key")

AFAIK, changing this to caching the original filenames/structure is not possible.
Maybe you should ask this in the NGINX forums.

**Comment by webmap2015** [comment]
Thanks.
