### ISSUE TITLE
serveAllData similar to serveAllStyles

### ISSUE THREAD

**Issue by xabbu42** [maptiler/tileserver-gl#436]
The latest version of tileserver-gl included the very useful serveAllStyles option to automatically pickup any styles (and changes to them) in a directory. This allowed us to get rid of quite some (automatically generated) config for tileserver-gl and just enable this option. It also means we need less restarts of tileserver-gl to update styles.

We could use the same feature for our data mbtiles, i.e. a serveAllData option which serves all mbtiles found in a directory and also watches for changes in that directory. With that option we could use small constant tileserver-gl config without any automatically generated part.

I wondered if this is already planed as it seems a logical next step. If not would a pull request be accepted and are there any known pitfalls in attempting to do this?

**Comment by idtstudios** [comment]
This would be a very useful feature

**Comment by r0hitsharma** [comment]
Duplicates #368, also check out #455

**Comment by xabbu42** [comment]
ok, closing this issue in favor of #368.
