### ISSUE TITLE
Preview thumbnail missing for raster data source – file suffix "undefined"

### ISSUE THREAD

**Issue by hfs** [maptiler/tileserver-gl#440]
With v3.0.0 of tileserver-gl and a raster data source in JPG format, the preview thumbnail image on the overview page is missing.

![preview_missing](https://user-images.githubusercontent.com/538109/80021312-97a2fe80-84da-11ea-81a7-bda0593f55d3.png)

To reproduce:

* Clone tileserver-gl v3.0.0, `npm install`
* Create a directory `data`, add a file `data/config.json` with:
    ```json
    { "data": { "satellite": { "mbtiles": "satellite.mbtiles" } } }
    ```
* Provide raster tiles in JPG format, e.g. by downloading https://openmaptiles.com/downloads/tileset/satellite/europe/germany/berlin/ and storing the file as `data/satellite.mbtiles`.
* Run tileserver-gl: `node src/main.js --config data/config.json`
* Open http://localhost:8080/. The overview page lists the available tile and data sources as expected – in this case there is only one.
* The preview thumbnail image is missing, though.

A request is made to `http://localhost:8080/data/satellite/13/4402/2690.undefined`, with the invalid file type `undefined`. When changing the URL to end in `.jpg` the request works.

**Comment by shihlinlu** [comment]
Hello, has the latest change been pushed to DockerHub? I see the latest merge to the master branch was 27 days ago, which includes the fix for fixing the preview image. However, the latest version for the Docker container has not been updated. https://hub.docker.com/r/maptiler/tileserver-gl
