### ISSUE TITLE
Docker image outdated

### ISSUE THREAD

**Issue by spwarner** [maptiler/tileserver-gl#444]
The image on Docker Hub is still for v2.6, while v3.0 has been released for months. Please update the klokantech/tileserver-gl:latest image to v3.0

**Comment by klokan** [comment]
Dockerhub doesn't support redirects. :-(


Perhaps we could remove the KlokanTech image entirely (including older tags) or better make a docker image just printing "please get the latest docker image from maptiler/tileserver-gl"?

**Comment by shihlinlu** [comment]
Thumbnail image previews are still broken in `maptiler/tileserver-gl:latest`. 

They are working correctly in the `klokantech` image though.

![Uploading maptiler v3.png…]()

**Comment by zingi** [comment]
> Please use the new `maptiler/tileserver-gl:latest` - it has the newer versions.
> 
> Dockerhub doesn't support redirects. :-(
> 
> Perhaps we could remove the KlokanTech image entirely (including older tags) or better make a docker image just printing "please get the latest docker image from maptiler/tileserver-gl"?

You could add "please get the latest docker image from maptiler/tileserver-gl" to the readme of https://hub.docker.com/r/klokantech/tileserver-gl on docker hub.

**Comment by petrsloup** [comment]
> > Please use the new `maptiler/tileserver-gl:latest` - it has the newer versions.
> > Dockerhub doesn't support redirects. :-(
> > Perhaps we could remove the KlokanTech image entirely (including older tags) or better make a docker image just printing "please get the latest docker image from maptiler/tileserver-gl"?
> 
> You could add "please get the latest docker image from maptiler/tileserver-gl" to the readme of https://hub.docker.com/r/klokantech/tileserver-gl on docker hub.

Message added :+1:
