### ISSUE TITLE
always misses the Mapbox access token 

### ISSUE THREAD

**Issue by Adurna17** [maptiler/tileserver-gl#447]
Hello friends of IT, 
I have a small problem with tileserver-gl. 
I am trying to create a mapserver with all the trimmings. And i would like to add some selfmade styles to this server. There are some bugs and so I decided to use the standard style dark_matter.json. 
Unfortunately, whenever I start the server on the Ubuntu 18.04 system (tileserver-gl config) an error occurs. 

>Starting tileserver-gl 
Using specified config file from config.json
Starting server
Listening at http://[::]:8080/
Startup complete
GET /mapbox-gl.css - - ms - -
GET /mapbox-gl-rtl-text.js 200 2.899 ms - 206897
GET /styles/dark/style.json 200 5.003 ms - 19527
GET /mapbox-gl-rtl-text.js 304 1.539 ms - -
GET /mapbox-gl-rtl-text.js 304 0.451 ms - -
GET /mapbox-gl-rtl-text.js 304 0.401 ms - -
GET /mapbox-gl-rtl-text.js 304 0.445 ms - -

It starts but when I try to see the style in the browser the 304 messages come up. 

here is my config.json file 

> {
  "options": {
    "paths": {
      "root": "/home/benni/map/mapServer/",
      "fonts": "fonts",
      "sprites": "sprites",
      "styles": "styles",
      "mbtiles": "data/"
    },
    "domains": [
      "localhost:8080",
      "127.0.0.1:8080"
    ],
    "formatQuality": {
      "jpeg": 80,
      "webp": 90
    },
    "maxScaleFactor": 3,
    "maxSize": 2048,
    "pbfAlias": "pbf",
    "serveAllFonts": false,
    "serveAllStyles": false,
    "serveStaticMaps": true,
    "tileMargin": 0
  },
  "styles": {
    "dark": {
      "style": "dark_matter.json",
      "serve_rendered": false,
      "tilejson": {
        "type": "overlay",
        "bounds": [
          87.99765,
          18.58403,
          92.69043,
          26.64677
        ]
      }
    }
  },
  "sources": {
    "World": {
      "url": "mbtiles://v3",
      "type": "vector"
    }
  },
  "data": {
    "v3": {
      "mbtiles": "2017-07-03_planet_z0_z14.mbtiles"
    }
  }
}

Is this a problem for me or in tileserver-gl?

**Comment by scara** [comment]
Hi @Adurna17,
`304` means _Not Modified_ i.e. your browser is asking the "web server" the grant to use its local cached copy of the resource and the quick round trip on _tileserver-gl_ grants it via that specific HTTP Status.
Ref.: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

HTH,
Matteo

**Comment by Adurna17** [comment]
Hello, 
thanks for the quick help and apologies for the slow response. 
I understand that 304 is not such a big problem. 
I hope it is not a big problem if I ask a new question if we are still in the old issue. 
I have seen in the article [here](https://github.com/maptiler/tileserver-gl/issues/89) that you can work in the npm project tileserver-gl without mapbox access token if you remove all references to mapbox from the resources. I have done that and unfortunately the error still comes 
`Error: "An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes"`
config.json: 

> {
  "options": {
    "paths": {
      "root": "/home/benni/map/mapServer/node_modules/tileserver-gl-styles",
      "fonts": "/home/benni/map/mapServer/fonts",
      "sprites": "/home/benni/map/mapServer/sprites",
      "styles": "/home/benni/map/mapServer/styles",
      "mbtiles": "/home/benni/map/mapServer/data/"
    },
    "domains": [
      "localhost:8080",
      "127.0.0.1:8080"
    ],
    "formatQuality": {
      "jpeg": 80,
      "webp": 90
    },
    "maxScaleFactor": 3,
    "maxSize": 2048,
    "pbfAlias": "pbf",
    "serveAllFonts": false,
    "serveAllStyles": false,
    "serveStaticMaps": true,
    "tileMargin": 0
  },
  "styles": {
    "dark": {
      "style": "ultimative.json",
      "serve_rendered": false,
      "tilejson": {
        "type": "overlay",
        "bounds": [
          87.99765,
          18.58403,
          92.69043,
          26.64677
        ]
      }
    }
  },
  "sources": {
    "World": {
      "url": "mbtiles://v3",
      "type": "vector"
    }
  },
  "data": {
    "v3": {
      "mbtiles": "2017-07-03_planet_z0_z14.mbtiles"
    }
  }
}

style json-file: 

> "version": 8,
    "name": "Dark Matter 12",
    "sources": {
      "openmaptiles": {
        "type": "vector",
        "url": "mapbox://2017-07-03_planet_z0_z14.mbtiles"
      }
    },
    "sprite": "",
    "glyphs":"https:///fonts/{fontstack}/{range}.pbf",
    "layers": [
      {

Optional to the style-file I also tried this but I did not know if this is the reference. 

> "version": 8,
  "name": "Dark Matter",
  "metadata": {
    "mapbox:autocomposite": false,
    "mapbox:type": "template",
    "mapbox:groups": {
      "b6371a3f2f5a9932464fa3867530a2e5": {
        "name": "Transportation",
        "collapsed": false
      },
      "a14c9607bc7954ba1df7205bf660433f": {"name": "Boundaries"},
      "101da9f13b64a08fa4b6ac1168e89e5f": {"name": "Places", "collapsed": false}
    },
    "openmaptiles:version": "3.x",
    "openmaptiles:mapbox:owner": "openmaptiles",
    "openmaptiles:mapbox:source:url": "mapbox://openmaptiles.4qljc88t",
    "maputnik:renderer": "mbgljs"
  },
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mapbox://2017-07-03_planet_z0_z14.mbtiles"
    }
  },
  "sprite": "",
  "glyphs": "https:///fonts/{fontstack}/{range}.pbf",
  "layers": [

Could you tell me why the problem keeps coming? or is there already an issue about how to build this npm project without access token? 
Thanks in advance and best regards 

Benni

**Comment by Adurna17** [comment]
I found my problem. 
It was the initialization of the "url": "mapbox://2017-07-03_planet_z0_z14.mbtiles" but the right one was "url": "mbtils://2017-07-03_planet_z0_z14.mbtiles" must be called. 
I mark the problem as solved
