### ISSUE TITLE
Labels showing on built-in TSGL viewer but not on external clients

### ISSUE THREAD

**Issue by alexbeeston** [maptiler/tileserver-gl#452]
I am using TSGL to serve tiles to a Cesium client. I want the tiles to be raster satellite images with state boundaries, roads, and region names overlaid on top. It is best to send the raster images and the vector data as two separate URLS to Cesium and then let Cesium overlay them. I can successfully send the imagery to Cesium as raw, unstyled, imagery. I can also send the boundaries and roads as styled vector data. They are overlaid by Cesium in image 1:
![image1](https://user-images.githubusercontent.com/48226198/83460928-d060bc80-a424-11ea-81a8-e407704d26bb.PNG)

However, when I add layers to style.json for the labels, the map looks exactly the same. I've downloaded the most recent version of the styles and I'm currently using OSM planet data version 3.11, as #271 has suggested. Note that changing "{name:latin}\n{name:nonlatin}" to "{name_en}" in style.json as suggested in #267 did not work. Unlike #267, where the labels cannot be seen in the TSGL viewer, I can see my labeled, transparent vector data in the TSGL viewer (see image 2)
![image2](https://user-images.githubusercontent.com/48226198/83461284-8b895580-a425-11ea-9be9-5e3341a5cb78.PNG).

This suggests TSGL recognizes my fonts, styles, etc., since it can render the text in its own viewer. But, when I send the labeled tiles over to Cesium, the text is lost. The console does not provide any error messages. I believe this is a TSGL issue because the same thing happens when I use Leaflet as my client instead of Cesium. 

I'm using the latest docker image of TSGL on a CentOS 7 VM, and the vector data is "osm-2020-04-06-v3.11-planet.mbtiles".

Can anyone help get geographic labels to render just as well as the state boundaries and roads did? Thanks

**Comment by alexbeeston** [comment]
The issue is resolved. I'm fairly certain is was nothing more than fixing a mis-configured port number on the URL to the glyphs key of the style.json files. Sorry for the false alarm.

**Comment by ftballguy45** [comment]
what was the fix here? for people who stumble upon this thread who are having an issue with no labels appearing
