### ISSUE TITLE
Tileserver npm will not install

### ISSUE THREAD

**Issue by shawty** [maptiler/tileserver-gl#474]
Tileserver will not install.

When following the instructions on the first page of this repository for an NPM install, I get the following error

![image](https://user-images.githubusercontent.com/1876454/93259150-4b14d400-f797-11ea-8a06-68c8bebfb595.png)

It would appear that the mapbox dependency that tile server depends on, is now behind an authenticated endpoint on S3 and not available to NPM during the install phase.

**Comment by shawty** [comment]
Looks like "Project-OSRM" have a similar issue with thier build system.

https://github.com/Project-OSRM/osrm-backend/issues/4228

I'm Going to try thier work around against Tile server, see if it works.

**Comment by shawty** [comment]
Workround in OSRM project seems to work, in so much as it allows the install to go ahead.

![image](https://user-images.githubusercontent.com/1876454/93259890-78ae4d00-f798-11ea-9f30-31b2659895e3.png)

**Comment by shawty** [comment]
It seems even with the work around something still does not install correctly, as not even "help" is available on the server

![image](https://user-images.githubusercontent.com/1876454/93261689-fb380c00-f79a-11ea-9606-6c0aa71bfe14.png)

**Comment by shawty** [comment]
Tileserver lite, installs and works fine, without any work arounds or hacks.

**Comment by petrsloup** [comment]
The tileserver-gl requires node 10, because of precompiled native dependencies (see https://github.com/maptiler/tileserver-gl#get-started and https://github.com/maptiler/tileserver-gl/blob/master/package.json#L13). You are using node 12, so that's why downloading of the dependencies fails.

**Comment by shawty** [comment]
@petrsloup I thought that myself initially, so I tried to install on my windows machine which has Node V10, and I got the same failure, 403 downloading the dependencies from S3.

![image](https://user-images.githubusercontent.com/1876454/93323716-df6d4e00-f80c-11ea-8dde-21d82dce363c.png)

![image](https://user-images.githubusercontent.com/1876454/93323792-f6ac3b80-f80c-11ea-8e42-3577544fb967.png)

As you can see, it fails with Node 10 too, so I don't think this is a Node version problem.

Once the packages are installed, Yes, I agree it then becomes a node problem (I've verified this by trying a manual build) but running the install via npm install fails for both V10 and V12 node js installs.
