### ISSUE TITLE
Update Docker Hub image

### ISSUE THREAD

**Issue by zstadler** [maptiler/tileserver-gl#476]
The [Docker Hub image](https://hub.docker.com/r/maptiler/tileserver-gl) was last updated on 11-Mar-2020.
It is currently 8 commits behind master.

@lhsm [requested an update](https://github.com/maptiler/tileserver-gl/pull/413#issuecomment-657981996) of the docker image on 14-July-2020

**Comment by zstadler** [comment]
Temporary workaround for `openmaptiles` users:
Modify `Makefile`

```diff
- 	docker pull maptiler/tileserver-gl
+ 	#docker pull maptiler/tileserver-gl
+       docker build -t maptiler/tileserver-gl https://github.com/maptiler/tileserver-gl.git
```

@lhsm

**Comment by petrsloup** [comment]
v3.1.0 released and docker image updated
