### ISSUE TITLE
How to properly check if the tileserver is running

### ISSUE THREAD

**Issue by georgbachmann** [maptiler/tileserver-gl#493]
We are using tileserver-gl to serve vector and raster data for our maps.
Currently we have three servers running, and a HAproxy in front to balance load. The problem is that we don't really know how to really check if the tileserver is up and running. Startup takes about 5-10 minutes, but it already accepts requests during that time.
So we'd like to have a mechanism to check is the server is already started up. What would be the right way to do that?

Also we noticed that today one of out tileservers wasn't responding any more with content. To the logs showed a request but `---` instead of a valid status-code. What would be the correct approach to check for that?

**Comment by xabbu42** [comment]
You can use `localhost:8080/health` for that. This only returns the string OK if startup has finished.

**Comment by zstadler** [comment]
@georgbachmann,
Can you close this issue?
