### ISSUE TITLE
Port Changed from 80 to 8000?

### ISSUE THREAD

**Issue by boldtrn** [maptiler/tileserver-gl#502]
I just check `3.1` and it seems that the internal port of the docker container changed from 80 to 8000.

So instead of running: `docker run --rm -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl` I had to run `docker run --rm -it -v $(pwd):/data -p 8080:8000 maptiler/tileserver-gl`.

Anyone saw the same issue?

**Comment by petrsloup** [comment]
Oversight in #457, fixed in v3.1.1

**Comment by boldtrn** [comment]
@petrsloup thanks for the fast fix, but I think this did not work. Since we are using the user [node](https://github.com/maptiler/tileserver-gl/pull/457/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R51), that users is probably not allowed to open port 80?

Using a non-root user is a good decision, but maybe we should actually switch to port 8000 and update the documentation? Maybe releasing this as v4, since it's a breaking change?
