### ISSUE TITLE
Failed to start when run via Docker when set options

### ISSUE THREAD

**Issue by zouyaoji** [maptiler/tileserver-gl#513]
```bash
sudo docker run --rm -it -v $(pwd)/data/mbtiles:/data -p 9001:80 maptiler/tileserver-gl -C
```

In the latest version, if the option "-C" is added, the service cannot be accessed. The v3.0.0 version does not have this problem.

**Comment by StefanBrand** [comment]
`-c` also doesn't work and you must use `--config`. Maybe only `--no-cors` works.

**Comment by zouyaoji** [comment]
Test passed in version v4.3.4 using --no-cors

**Comment by marhensa** [comment]
sorry to ask here. 
how do you solve this @zouyaoji ? I still get CORS error when consume output json tile.

tested in latest 4.5.0

```
docker run -d \
  --name tileserver-gl \
  --restart unless-stopped \
  -it \
  -v /mnt/e/labs/dockerwsl/volume-stuff/tileserver-gl:/data \
  -p 6080:8080 \
  maptiler/tileserver-gl:latest \
  --no-cors
```
