### ISSUE TITLE
--mbtiles for Docker does not work!!!

### ISSUE THREAD

**Issue by adriantabirta** [maptiler/tileserver-gl#518]
Run
`docker run --rm -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl --mbtiles=moldova.mbtiles --verbose`
it runs ok

Go to:
`localhost:8080/` and get `Error: socket hang up`

`docker run --rm -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl` - runs ok, I can see the page

**Comment by samuel-litzler** [comment]
any solutions ?
