### ISSUE TITLE
Cache-Control

### ISSUE THREAD

**Issue by georgbachmann** [maptiler/tileserver-gl#543]
Just a very simple quick question...

We just noticed that tileserver-gl responses do not include a Cache-Control header. Is it possible to add some using tileserver-gl or should we do so in our varnish cache?

**Comment by mnutt** [comment]
You could set it in tileserver-gl but it would involve modifying the code and maintaining a fork; the varnish cache config would probably be an easier place to set it.

**Comment by georgbachmann** [comment]
Yep... we solved our problem using the varnish cache headers! Thanks for your answer though!
Cheers

**Comment by 2803media** [comment]
hi @georgbachmann could you please share your varnish config i'm stuck with it right now in my docker config? Tx

**Comment by georgbachmann** [comment]
@2803media we ended up using ATS (appache traffic server) for our caching, as we could not invalidate individual tiles using varnish (unlong we pay a looooooot per year)
If it's still relevant to you with ATS, i could ask the person who did it how... I don't know much about that kind of black-magic :)

**Comment by 2803media** [comment]
> @2803media we ended up using ATS (appache traffic server) for our caching, as we could not invalidate individual tiles using varnish (unlong we pay a looooooot per year) If it's still relevant to you with ATS, i could ask the person who did it how... I don't know much about that kind of black-magic :)

Thanks for your reply and you are happy with the performance with ATS (which I never try ;)), if you have more information on the setup I will be happy to try it!
