### ISSUE TITLE
Specify config file

### ISSUE THREAD

**Issue by carlodenardin** [maptiler/tileserver-gl#564]
How can I specify the config.json file when I run my server?

`docker run --rm --user=501:20 -it --name tileserver-gl -v $(pwd)/data:/data -p 8080:8080 maptiler/tileserver-gl --port 8080 --verbose`

Because I don't want the automatic config.json which mess up my mbtiles files. This is the automatic file:

```
{
  "options": {
    "paths": {
      "root": "/app/node_modules/tileserver-gl-styles",
      "fonts": "fonts",
      "styles": "styles",
      "mbtiles": "/data"
    }
  },
  "styles": {},
  "data": {
    "contour": {
      "mbtiles": "contour.mbtiles"
    }
  }
}
```

as you can see in the automatic file the data are just the contour. Instead I need to add a specific config.json since I want to add the tile.mbtiles, hillshade.mbtiles and the contour.mbtiles. I tried with -c but is not working.

**Comment by scara** [comment]
Hi @carlodenardin,
you can use any config file by means of the following argument: `-c, --config <file>`.
You can add your config file within your `data/` directory and then add `-c /data/config.json` to your command line.

HTH,
Matteo
