### ISSUE TITLE
Disappearing Lines

### ISSUE THREAD

**Issue by altilunium** [maptiler/tileserver-gl#598]
https://user-images.githubusercontent.com/70379302/187366271-43a3312d-aa94-46bc-836b-9d3d84a37ab6.mp4

How to prevent disappearing lines like this? What is the cause? 

Here is my source-code, if anyone want to reproduce it.

[kpatas.zip](https://github.com/maptiler/tileserver-gl/files/9450282/kpatas.zip)

`tileserver-gl-light kpatas.mbtiles -p 8083 -c a.json`

**Comment by acalcutt** [comment]
I tested it here in chrome with v4.0.0 and v3.1.0 and neither seemed to have this issue.  I was able to zoom in and out on those roads and nothing disappeared.

What browser are you sing there?
