### ISSUE TITLE
Markers at static map [tileserver + MapTiler]

### ISSUE THREAD

**Issue by gnorb** [maptiler/tileserver-gl#601]
Hi,
according to MapTiler docs, I created server with tileserver-gl and imported MapTilers vectors into it. Now I see there is no way to render markers on static map, like [MapTiler docs](https://www.maptiler.com/news/2019/01/static-maps-on-maptiler-cloud/) says.  

Is there any possibility to render markers on static map by tileserver?

**Comment by klokan** [comment]
The documentation is for MapTiler Cloud - not for TileServer GL.
Go to https://cloud.maptiler.com/maps/streets-v2/static

**Comment by acalcutt** [comment]
There is a PR to add marker support to static images here https://github.com/maptiler/tileserver-gl/pull/619 . Do you think that is something you could use? Any reviews of the PR are welcome.

**Comment by acalcutt** [comment]
https://github.com/maptiler/tileserver-gl/pull/619 has been merged, so there is now some basic marker support.

Basically, you need to specify an 'icons' path in your config file. In this location you need to put your marker images. There are instructions here ( https://github.com/maptiler/tileserver-gl/blob/master/docs/endpoints.rst ) . I put some examples in the PR at https://github.com/maptiler/tileserver-gl/pull/619#issuecomment-1270863448

Note, the instruction should show at https://tileserver.readthedocs.io/en/latest/endpoints.html#static-images but they have not seemed to update yet.
