### ISSUE TITLE
Update image on Docker hub

### ISSUE THREAD

**Issue by rudokemper** [maptiler/tileserver-gl#607]
Great to see the new changes to use MapLibre GL! Now might be a good time to update the [image on Docker hub as well](https://hub.docker.com/r/maptiler/tileserver-gl), since self-hosted tiles are not loading due to forced authentication with the Mapbox.com API. 

In the same stroke, you could use buildx to create the image so that it will work on arm architecture.

**Comment by acalcutt** [comment]
I am working on a v4.0.0 release, so hopefully soon. I am trying to update the remaining packages and documentation for a release.

**Comment by acalcutt** [comment]
I released V4.0.0 on [github](https://github.com/maptiler/tileserver-gl/releases/tag/v4.0.0), [maptiler/tileserver-gl](https://hub.docker.com/r/maptiler/tileserver-gl/tags) on docker, and [tileserver-gl](https://www.npmjs.com/package/tileserver-gl) on npm . The main features of this is the move to [#maplibre-native](https://osmus.slack.com/archives/C02B2CBSNBU), which allows us to move past node 10 and update all our packages to fix some vulnerabilities. The frontend templates have also been upgraded [#maplibre-gl-js](https://osmus.slack.com/archives/C03TFH5NE83) and leaflet. This does not yet included the light version yet, I still need some permissions to get that posted.

**Comment by acalcutt** [comment]
This should be all set, all the v4.0.0 docker and npm images have been uploaded.

**Comment by rudokemper** [comment]
Thanks for this! @acalcutt
