### ISSUE TITLE
NPM Registry: tileserver-gl-light not updated to 4.0.0

### ISSUE THREAD

**Issue by scara** [maptiler/tileserver-gl#614]
Hi @acalcutt,
4.0.0 has been published as [NPM package](https://www.npmjs.com/package/tileserver-gl) [but the _light_ version](https://www.npmjs.com/package/tileserver-gl-light): is that a missing?
https://github.com/maptiler/tileserver-gl/pull/602 touched the _light_ option too.

Thanks in advance,
Matteo

**Comment by acalcutt** [comment]
I do plan to do it at some point, but I need to request permission from @klokan . He granted me permission to the tileserver-gl docker and npm, but not  tileserver-gl-light. I'll reach out to him to see if I can get the access there too.

The main fixes in the light version would be maplibre-gl-js/leaflet in the templates. I also added a docker entry point file which allows the light version to close properly with ctrl-c like the non-light version (before this ctrl-c didn't work)

**Comment by scara** [comment]
TNX for your very quick reply!
Appreciated.

**Comment by acalcutt** [comment]
I released the v4.0.0 tileserver-gl-light on npm. 

It doesn't look like there was a maptiler/tileserver-gl-light docker release before, so I can't quite publish that yet.

**Comment by acalcutt** [comment]
the docker for tileserver-gl-light is up now too https://hub.docker.com/r/maptiler/tileserver-gl-light , Thanks @klokan

**Comment by scara** [comment]
TNX @acalcutt too 😉 !
