### ISSUE TITLE
Vector working, but raster tiles time out - mbtiles vector source

### ISSUE THREAD

**Issue by stagehand01** [maptiler/tileserver-gl#615]
Hi team

I am running Tile Server GL via the current Docker image on AWS EC2 / Ubuntu.

I have a source mbtile vector source generated via QGIS ("Write Vector Tiles (MBTiles)"), zoom levels 0 to 14. I have tried a few different files with different data (points, lines, polygons) with the same result.

I want to use Tile Server to render the vector mbtiles file as raster using the WMTS endpoint. 

Running the "demo" docker, this works fine. I can access the raster endpoints via the demo page, however if I replace the input file with my own, all raster functionality stops working. I can still see the vector "Inspect" option, and that works fine, but any raster request times out. Tile Server displays the request on the console when it times out, but doesn't have an HTTP return code. 

No other errors or warnings are displayed, either when the Docker image starts or in response to HTTP requests. 

Any suggestions on what could cause this behaviour? 

This is what the output looks like from the Docker image when I use the "Raster" option from the main page:

GET /styles/fen/2/1/1.png - - - - ms
GET /styles/fen/2/1/2.png - - - - ms
GET /styles/fen/2/2/2.png - - - - ms
GET /styles/fen/2/1/0.png - - - - ms

**Comment by acalcutt** [comment]
can you share a sample mbtiles file with the issue you mentioned?

**Comment by kgebels** [comment]
Hi, yes, I've attached it here. This is a vector mbtile from QGIS on Windows, generated from a shape file of online/free demo data. I've tried other vector mbtiles too, with the same result.

Looks fine in the "Inspect" section, but the "Raster" section generates requests for .png files, which time out. 

I've also attached the config and style we're using. Have tried to simplify it for the purposes of demonstrating the issue we're having.

This looks like a great solution and we're very excited at using it, just need to get the WMTS working for these vector mbtiles.

Many thanks
[firehistory.mbtiles.zip](https://github.com/maptiler/tileserver-gl/files/9669714/firehistory.mbtiles.zip)
[uploaded_style.json.txt](https://github.com/maptiler/tileserver-gl/files/9669723/uploaded_style.json.txt)
[uploaded_config.json.txt](https://github.com/maptiler/tileserver-gl/files/9669724/uploaded_config.json.txt)

**Comment by acalcutt** [comment]
I re-worked your config and style a bit and was able to get it to work
[test_revised.zip](https://github.com/maptiler/tileserver-gl/files/9670426/test_revised.zip)

![image](https://user-images.githubusercontent.com/3792408/192927696-4c2e466c-c556-4d3d-a157-8bf95c8e9419.png)

**Comment by stagehand01** [comment]
Thanks very much, I've loaded that up and confirmed the raster output is working. Love your work, this is a great tool.

We'll take a look at the config/style updates to learn where we went wrong.
