### ISSUE TITLE
Why can't the Chinese text-field in rasterized mode be displayed under the same mbtiles file and style? Ask how to solve?

### ISSUE THREAD

**Issue by zzkzzk1984** [maptiler/tileserver-gl#621]
Why can't the Chinese text-field in rasterized mode be displayed under the same mbtiles file and style? Ask how to solve?

Screenshot of vector mode：
![image](https://user-images.githubusercontent.com/23081513/194115711-a1fae026-1776-4b06-b00b-365f0a295de1.png)

Screenshot of rasterized mode：
![image](https://user-images.githubusercontent.com/23081513/194115378-00db9391-acc1-478d-80e7-01ab322a8128.png)

Screenshot of style.json:
![image](https://user-images.githubusercontent.com/23081513/194115194-7fc6a64e-d302-4ab5-8e9a-dc6eef6666af.png)

**Comment by acalcutt** [comment]
I don't have any solution at this tile, but I tested this on my server and can confirm the issue. it seems like any text that has chinese characters is not showing

With maplibre-gl-js
https://tiles.wifidb.net/styles/WDB_BASIC/#8/22.022/106.885
![image](https://user-images.githubusercontent.com/3792408/194124149-1fed20d1-5efe-4815-8bd6-916afb72dba4.png)

With maplibre-gl-native
https://tiles.wifidb.net/styles/WDB_BASIC/?raster#9/22.0220/106.8846
![image](https://user-images.githubusercontent.com/3792408/194124281-4c59ad0e-6918-4d19-9f64-411cbde28338.png)

**Comment by acalcutt** [comment]
After some more testing I got it working. In my case it was because I did not have to Noto fonts in font directory specified in my config file.

I went and downloaded [noto-sans.zip](https://github.com/openmaptiles/fonts/releases/download/v2.0/noto-sans.zip) from https://github.com/openmaptiles/fonts/releases ,restarted tileserver, and now those chinese symbols show.

![image](https://user-images.githubusercontent.com/3792408/194139488-d79229ce-2b33-492d-8379-db872df70b4b.png)

**Comment by zzkzzk1984** [comment]
> After some more testing I got it working. In my case it was because I did not have to Noto fonts in font directory specified in my config file.
> 
> I went and downloaded [noto-sans.zip](https://github.com/openmaptiles/fonts/releases/download/v2.0/noto-sans.zip) from https://github.com/openmaptiles/fonts/releases , put them in my fonts directory, restarted tileserver, and now those chinese symbols show.
> 
> ![image](https://user-images.githubusercontent.com/3792408/194139752-80c75d2c-ed7e-45bc-b3d9-247a5dc916a5.png)
With your patient help, I have solved this problem, thank you so much！
![image](https://user-images.githubusercontent.com/23081513/194207536-a67bc87b-e99d-4755-b1c7-0ee8f32d1961.png)
