### ISSUE TITLE
Using SIGHUP to restart is not working

### ISSUE THREAD

**Issue by trondat** [maptiler/tileserver-gl#629]
Hi,

I have used SIGHUP to restart the server earlier, this has worked fine. With the current verison it just responds with "Hangup" and then the server stops responding. 

I'm running tileserver-gl in Docker and sends the command to the server like this :
`docker exec tileserver-gl bash -c 'kill -HUP $(ls -l /proc/*/exe | sed -n "/\/node$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p")' `

This gives : 
```Starting server
Listening at http://[::]:80/
Startup complete
Hangup
```
After this it stops responding.

Is there some way of working around this ?

**Comment by acalcutt** [comment]
This seems to be related to https://github.com/maptiler/tileserver-gl/pull/575

If I remove this section added to docker-entrypoint.sh, the process ends.
```
	while [ ${RETVAL} = 129 ] ; do
		echo 
	  # Refressh signal HUP received. Continue waiting for signals.
	  wait $! || RETVAL=$?
	done
```

**Comment by acalcutt** [comment]
the is some updated documentation relating to that at https://tileserver.readthedocs.io/en/latest/usage.html . `docker kill -s HUP tileserver-gl` did work for me once I gave my run a name.

Though reading it I feel like this was originally supposed to be more of a refresh, but it seems like a kill... (maybe so docker will automatically refresh?)

**Comment by zstadler** [comment]
@trondat ,

Please reload the configuration using the method described in [the documentation](https://tileserver.readthedocs.io/en/latest/usage.html#reloading-the-configuration):

> Reloading the configuration
> ======
> 
> It is possible to reload the configuration file without restarting the whole process by sending a SIGHUP signal to the node process.
> 
> - The `docker kill -s HUP tileserver-gl` command can be used when running the tileserver-gl docker container.
> - The `docker-compose kill -s HUP tileserver-gl-service-name` can be used when tileserver-gl is run as a docker-compose service.

The `docker-entrypoint.sh` shell script and [the documentation](https://github.com/maptiler/tileserver-gl/pull/560/files#diff-c4b284a0e8c330264ebefb4d3d14dd5bb68fe3b72c2ae656f49132e2c134b84f) were updated in #560 and #575 to avoid the need for the complex `docker exec` command required earlier:

```
- When running the tileserver-gl docker container, the signal must be sent from within the container:
- ::

- -   docker exec tileserver-gl bash -c 'kill -HUP $(ls -l /proc/*/exe | sed -n "/\/node$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p")'
+ - The `docker kill -s HUP tileserver-gl` command can be used when running the tileserver-gl docker container.
+ - The `docker-compose -s HUP tileserver-gl-service-name` can be used when tileserver-gl is run as a docker-compose service.

**Comment by zstadler** [comment]
@acalcutt wrote:
> This seems to be related to https://github.com/maptiler/tileserver-gl/pull/575/files

In fact, the old way of reloading the configuration, as used by @trondat, bypasses `docker-entrypoint.sh` and  sends the `HUP` signal directly to the `node` process that runs `tileserver-gl`:
```
docker exec tileserver-gl bash -c 'kill -HUP $(ls -l /proc/*/exe | sed -n "/\/node$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p")' 
```

It finds the required process number by running
```
ls -l /proc/*/exe | sed -n "/\/node$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p
```
in the active container. In a line like this it extracts `37` as the process number of `node`:
```
lrwxrwxrwx 1 node node 0 Oct 27 08:07 /proc/37/exe -> /usr/local/bin/node
```

**Comment by trondat** [comment]
Ok.. So you are saying that trying to send SIGHUP to the node process is wrong and should not work ?

I see in the JS code (server.js) that there are handling of these signals, but this part of the code is never run.
```
export const exports = (opts) => {
  const running = start(opts);

  running.startupPromise.catch((err) => {
    console.error(err.message);
    process.exit(1);
  });

  process.on('SIGINT', () => {
    process.exit();
  });

  process.on('SIGHUP', () => {
    console.log('Stopping server and reloading config');

    running.server.shutdown(() => {
      for (const key in require.cache) {
        delete require.cache[key];
      }

      const restarted = start(opts);
      running.server = restarted.server;
      running.app = restarted.app;
    });
  });

  return running;
};
````

If this code was run it would set up the signal handling correctly, and sending HUP to the node process would trigger a reload of the config.

**Comment by zstadler** [comment]
> Ok.. So you are saying that trying to send SIGHUP to the node process is wrong and should not work ?

I recommended using the documented way to simplify the command and avoid potential errors. I did not say it doesn't work. 

In fact, the `node` process must receive a HUP signal to reload the configuration. It's all about the simplest way of doing so from the host computer while the node process runs in the docker container - using a `docker kill` command.

I think I've also [described](#issuecomment-1293174507) why  I believe this issue is unrelated to the `docker-entrypoint.sh` script in either its old or new implementations.

**Comment by zstadler** [comment]
@acalcutt wrote:
> ... but this part of the code is never run

Perhaps that's the cause of this issue

**Comment by trondat** [comment]
Hmmm.....

Cloning the latest code and building the docker image and running under local Docker yields this : 
```
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:80/
Startup complete
```

and then issuing Docker kill : 
```
docker kill -s HUP 05704c51b31f
```
Where  05704c51b31f is the container id gives the following : 
```
Caught signal 1, refreshing
Hangup
```
**And then the Tileserver stops responding to request. 
Back to square one.**

**Comment by zstadler** [comment]
This seems like a degradation between v4.0.0 and 4.1.1.

The log for running the scenario in v4.0.0 is:
```
Starting tileserver-gl v4.0.0
No MBTiles specified, using tiles.mbtiles
[INFO] Automatically creating config file for tiles.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:80/
Startup complete
Stopping server and reloading config
Starting server
Listening at http://[::]:80/
Startup complete
```

The log for v4.1.1 is:
```
Starting tileserver-gl v4.1.1
No MBTiles specified, using tiles.mbtiles
[INFO] Automatically creating config file for tiles.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:80/
Startup complete
Hangup
```

**Comment by zstadler** [comment]
The scenario I've used:

```
$ docker run --mount type=bind,src=`pwd`,dst=/data --detach --name tileserver-gl maptiler/tileserver-gl:v4.0.0
4e63a243b7fe8519dddb3bd8f8fea9004b67e4469ef00b3be75b869848e30f84
$ docker kill -s HUP tileserver-gl

tileserver-gl
$ docker logs tileserver-gl
Starting tileserver-gl v4.0.0
No MBTiles specified, using tiles.mbtiles
[INFO] Automatically creating config file for tiles.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:80/
Startup complete
Caught signal 1, refreshing
Stopping server and reloading config
Starting server
Listening at http://[::]:80/
Startup complete
```

**Comment by trondat** [comment]
Ok.

Thank you. 

To conclude there is either a bug in v4.1.1 or that part of the functionality has been removed. 
I will clone v4.0.0 and use that for now.

**Comment by acalcutt** [comment]
when i tested the command @trondat gave, it looks like it kills the node process, then gets stuck in the `while [ ${RETVAL} = 129` loop. the process never restarts so it just sits in that loop.

4.0.0 is likely not going to be different because the PR above was made in maych, before all the 4.0.0 release.

**Comment by trondat** [comment]
I pulled down 4.0.0 and it works as expected. 4.1.1 does not work !

**Comment by zstadler** [comment]
The degradation in v4.1.1 is in the node process.
The unexpected Hangup happens in v4.1.1 also when the HUP signal is sent directly to the node process:

#### V4.0.0
```
$ docker run --mount type=bind,src=`pwd`,dst=/data --detach --name tileserver-gl maptiler/tileserver-gl:v4.0.0
1d947fa156ac659be52d3246bdbd7494534373edcd276bbac89f87bd28861569
$ docker exec tileserver-gl bash -
$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p")'
$ docker logs tileserver-gl
Starting tileserver-gl v4.0.0
No MBTiles specified, using tiles.mbtiles
[INFO] Automatically creating config file for tiles.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:80/
Startup complete
Stopping server and reloading config
Starting server
Listening at http://[::]:80/
Startup complete
```

#### v4.1.1
```
$ docker run --mount type=bind,src=`pwd`,dst=/data --detach --name tileserver-gl maptiler/tileserver-gl:v4.1.1
f0a4b8c32beadd16a146cac07f43c661fde9da1bcdfe65875565edae960763bc
$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p")'
$ docker logs tileserver-gl
Starting tileserver-gl v4.1.1
No MBTiles specified, using tiles.mbtiles
[INFO] Automatically creating config file for tiles.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:80/
Startup complete
Hangup
```

**Comment by trondat** [comment]
I think the problem is that the signal listeners code in "server.js" in  4.1.1 is never run thereby the default behaviour of Node is run.

Here from Node doc : 

>  On non-Windows platforms, the default behavior of SIGHUP is to terminate Node.js, but once a listener has been installed its default behavior will be removed.

**Comment by acalcutt** [comment]
I don't think that is it. For example, if you add echo tho the docker entrypoint like

```
  xvfb-run -a --server-args="-screen 0 1024x768x24" -- node /usr/src/app/ -p 80 "$@" &
	# Wait exits immediately on signals which have traps set. Store return value and wait
	# again for all jobs to actually complete before continuing.
	wait $! || RETVAL=$?
	echo RETVAL
	while [ ${RETVAL} = 129 ] ; do
		echo RETVAL
		# Refressh signal HUP received. Continue waiting for signals.
		wait $! || RETVAL=$?
	done
	wait
	exit ${RETVAL}
```

and then run your kill command, you can see it just keeps echoing 129 which is the RETVAL being returned. So you command is killing node, which returns RETVAL 129, then it goes into that while loop and never comes out because node is not restarted.

My version here works, because it when node ends and retval is 129, it goes back to the top of the loop and starts node again.

**Comment by acalcutt** [comment]
It's strange there is a difference between 4.0.0 and 4.1.1... I don't think there were any changes in the docker between those versions.

**Comment by zstadler** [comment]
Both @trondat and myself have actually tested v4.0.0 and the reloading works. 

Put any mbtiles file in an empty directory and run the following commands to see that reloading works in v4.0.0 both ways:
1. Directly to the node process using `docker exec`
2. indirectly through the `docker-entrypoint.sh` script using `docker kill`

```
docker run --mount type=bind,src=`pwd`,dst=/data --detach --name tileserver-gl maptiler/tileserver-gl:v4.0.0
docker exec tileserver-gl bash -c 'kill -HUP $(ls -l /proc/*/exe | sed -n "/\/node$/s/.*proc\/\([0-9]\+\)\/exe .*/\1/p")'
docker kill -s HUP tileserver-gl
docker logs tileserver-gl
```

Similarly, the v4.1.1 node process hangs instead of reloading the configuration regardless of how the node process receives the HUP signal.

The  `docker-entrypoint.sh` script did not change between v4.0.0 and v4.1.1. This is another indication that the problem is not in the script.

@acalcutt, Please feel free to PM my on Slack

**Comment by zstadler** [comment]
> It's strange there is a difference between 4.0.0 and 4.1.1... I don't think there were any changes in the docker between those versions. the new ubuntu based docker came after 4.1.1 and has not yet been published on dockerhub.

Bugs are never found where you expect them 😢

**Comment by acalcutt** [comment]
v4.0.0 for sure worked with both like you said.

The major changes in 4.1.1 was converting it esm module and the systax change. I think commander was also updated in that process, so I wonder if that changed anything with the reloading.

**Comment by acalcutt** [comment]
it looks like in 4.1.1 it never echos "Stopping server and reloading config", which looks like it is in src/server.js

**Comment by acalcutt** [comment]
After talking with @zstadler I think we can say this was a change started at my major syntax change PR https://github.com/maptiler/tileserver-gl/pull/606

It seems like this section of code is never triggered https://github.com/maptiler/tileserver-gl/blob/master/src/server.js#L486-L496 and instead of reloading the config, node gets killed.

**Comment by acalcutt** [comment]
I release v4.1.2 which should fix this. can you let me know if that works for you

**Comment by trondat** [comment]
It works ok now, thank you very @acalcutt
