### ISSUE TITLE
why text-field can't display on raster mode even it can't work in raster mode,but in vector tile mode?what's the promble?how can i solve it?

### ISSUE THREAD

**Issue by 2496772010** [maptiler/tileserver-gl#640]
when i start  tileserver-gl with docker ,as long as  i use text-field related style ,the raster mode is not work.
these is sreenshot infomation,i need help
![QQ截图20221110150246](https://user-images.githubusercontent.com/46257447/201022862-89e6d4fe-cf65-42a3-89cf-f4083b50c043.png)
![QQ截图20221110150435](https://user-images.githubusercontent.com/46257447/201022919-04f74d3a-3a88-4674-b9a1-a82f9cdf7371.png)

![QQ截图20221110150044](https://user-images.githubusercontent.com/46257447/201022237-a508c1ac-7280-49ca-8a61-7552c32c4dc5.png)

![QQ截图20221110145836](https://user-images.githubusercontent.com/46257447/201021995-23da3092-7739-44fd-a727-01ef2b5522ec.png)

**Comment by acalcutt** [comment]
Can you share you config file and style? How are you running this, directly with node or with docker?

**Comment by 2496772010** [comment]
[tileservergl.zip](https://github.com/maptiler/tileserver-gl/files/9981813/tileservergl.zip)
yes,that's my style and config file. thank you!

**Comment by 2496772010** [comment]
otherwise i work it with docker

**Comment by acalcutt** [comment]
Can you try with this config and tell me if it works for you?

1.) In your 'mapbox-street-style.json', remove the first foward slash before {fontstack} in 
`"glyphs": "/{fontstack}/{range}.pbf"`
so it looks like
"glyphs": "{fontstack}/{range}.pbf"

2.) In your fonts folder, extract the [noto-sans.zip](https://github.com/openmaptiles/fonts/releases/download/v2.0/noto-sans.zip) fonts, so they are not inside a noto-sans folder. so they are at 
**fonts\Noto Sans Bold
fonts\Noto Sans Italic
fonts\Noto Sans Regular**
( i know in your screenshot you had a copy there too, but can you make sure it's the one from the zip, which has fixed chinese characters.)

3.) Make sure your sprites exist, maplibre-native rendering fails if they don't exists. your theme expects them in sprites/sprites.json

In the end it should looks something like this config ( + the fonts [noto-sans.zip](https://github.com/openmaptiles/fonts/releases/download/v2.0/noto-sans.zip) )
[test_data_china.zip](https://github.com/maptiler/tileserver-gl/files/9986127/test_data_china.zip)

When I test this here I get this
![image](https://user-images.githubusercontent.com/3792408/201252485-b25a2549-23c4-4977-b9e9-517d2841327b.png)

![image](https://user-images.githubusercontent.com/3792408/201252554-9b4c23c9-782b-4df3-9af5-ba4c4131088e.png)

**Comment by 2496772010** [comment]
Thank you very much, it works good！It help me a lot!
