### ISSUE TITLE
TileServer GL : issue with port 8080

### ISSUE THREAD

**Issue by raphael10-collab** [maptiler/tileserver-gl#646]
This is the current situation : 

O.S.: Ubuntu 22.04
Server : VPS Contabo Server

    root@vmi1046457:~# sudo docker run --restart=always -it -d -v /root/openmaptiles/data:/data -p 8080:80 maptiler/tileserver-gl
    9cfafc58933b3e8080c27b92463d276d1c46b718d28a59665a8cb5a945ebb905

    root@vmi1046457:~# docker ps
    CONTAINER ID   IMAGE                    COMMAND                  CREATED       STATUS                         PORTS                            NAMES
    9cfafc58933b   maptiler/tileserver-gl   "/usr/src/app/docker…"   2 hours ago   Up 2    
    hours (healthy)   8080/tcp, 0.0.0.0:8080->80/tcp   dazzling_colden

    root@vmi1046457:~# sudo ufw allow 8080/tcp
    Skipping adding existing rule
    Skipping adding existing rule (v6)

    root@vmi1046457:~# nc -l -p 8080 
    nc: Address already in use
    root@vmi1046457:~# 

     root@vmi1046457:~# netstat -an|grep LIST 
    tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
    tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
    tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN     
    tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
    tcp        0      0 127.0.0.1:42069         0.0.0.0:*               LISTEN     
    tcp6       0      0 :::22                   :::*                    LISTEN     
    tcp6       0      0 :::80                   :::*                    LISTEN     
    unix  2      [ ACC ]     STREAM     LISTENING     722894   /run/user/0/systemd/private
    unix  2      [ ACC ]     STREAM     LISTENING     722900   /run/user/0/bus
    unix  2      [ ACC ]     STREAM     LISTENING     722902   /run/user/0/gnupg/S.dirmngr
    unix  2      [ ACC ]     STREAM     LISTENING     722904   /run/user/0/gnupg/S.gpg-agent.browser
    unix  2      [ ACC ]     STREAM     LISTENING     722906   /run/user/0/gnupg/S.gpg-agent.extra
    unix  2      [ ACC ]     STREAM     LISTENING     21766    /var/run/docker/libnetwork/314b586c6194.sock
    unix  2      [ ACC ]     STREAM     LISTENING     722908   /run/user/0/gnupg/S.gpg-agent.ssh
    unix  2      [ ACC ]     STREAM     LISTENING     722910   /run/user/0/gnupg/S.gpg-agent
    unix  2      [ ACC ]     STREAM     LISTENING     2392     /run/acpid.socket
    unix  2      [ ACC ]     STREAM     LISTENING     2394     /run/dbus/system_bus_socket
    unix  2      [ ACC ]     STREAM     LISTENING     2396     /run/docker.sock
    unix  2      [ ACC ]     STREAM     LISTENING     2398     /run/uuidd/request
    unix  2      [ ACC ]     STREAM     LISTENING     18003    /run/systemd/private
    unix  2      [ ACC ]     STREAM     LISTENING     18005    /run/systemd/userdb/io.systemd.DynamicUser
    unix  2      [ ACC ]     STREAM     LISTENING     18006    /run/systemd/io.system.ManagedOOM
    unix  2      [ ACC ]     STREAM     LISTENING     18025    /run/systemd/journal/stdout
    unix  2      [ ACC ]     SEQPACKET  LISTENING     18028    /run/udev/control
    unix  2      [ ACC ]     STREAM     LISTENING     24635    /run/irqbalance/irqbalance509.sock
    unix  2      [ ACC ]     STREAM     LISTENING     19343    /run/systemd/journal/io.systemd.journal
    unix  2      [ ACC ]     STREAM     LISTENING     24666    /run/systemd/resolve/io.systemd.Resolve
    unix  2      [ ACC ]     STREAM     LISTENING     4612     /run/containerd/containerd.sock.ttrpc
    unix  2      [ ACC ]     STREAM     LISTENING     4614     /run/containerd/containerd.sock
    unix  2      [ ACC ]     STREAM     LISTENING     18235    /var/run/docker/metrics.sock
    unix  2      [ ACC ]     STREAM     LISTENING     2431     /var/run/postgresql/.s.PGSQL.5432
    unix  2      [ ACC ]     STREAM     LISTENING     795125   /run/containerd/s/dcb7b80af05b61e4b240a5af6588e095dab23ace3a0f87274e50fb6289c889c7
    
    
    root@vmi1046457:~# sudo nmap 194.60.201.224
    Starting Nmap 7.80 ( https://nmap.org ) at 2022-11-23 11:08 CET
    Nmap scan report for vmi1046457.contaboserver.net (194.60.201.224)
    Host is up (0.000062s latency).
    Not shown: 997 closed ports
    PORT     STATE    SERVICE
    22/tcp   open     ssh
    80/tcp   open     http
    8080/tcp filtered http-proxy
    
    Nmap done: 1 IP address (1 host up) scanned in 3.41 seconds
    root@vmi1046457:~# sudo ufw enable^C
    root@vmi1046457:~# 
    root@vmi1046457:~# 
    root@vmi1046457:~# 
    root@vmi1046457:~# sudo netstat -plant | grep 8080
    tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      188808/docker-proxy 

If I put in the browser address bar: http://194.60.201.224/ -> I correctly get: 

    Apache2 Default Page 

![image](https://user-images.githubusercontent.com/70313067/203539887-f37f3d3b-a068-4102-88d0-dde7b5412da9.png)

If If put: http://194.60.201.224:8080/ -> I get :

    This site can’t be reached194.60.201.224 refused to connect.
    Try:
    Checking the connection
    Checking the proxy and the firewall

![image](https://user-images.githubusercontent.com/70313067/203540043-ee3119aa-541f-4dca-abf9-198c8da4861a.png)

And:

    root@vmi1046457:~# curl 194.60.201.224
    curl: (7) Failed to connect to 194.60.201.224 port 8080 after 22 ms: Connection refused

What should I do in order to be able to connect to `:8080` ?

**Comment by acalcutt** [comment]
what command are you using to start docker? 8080:80 should be changed to 8080:8080 since v4.2.0

**Comment by raphael10-collab** [comment]
Thank you @acalcutt Andrew!

It was that issue...

I was following this guide (Step 9) , which, clearly, was not that updated: https://www.linuxbabe.com/ubuntu/basemap-tileserver-gl-openmaptiles-ubuntu-22-04#comment-830662

I changed from `8080:80` to `8080:8080` : 
    
    root@vmi1046457:~# sudo docker run --restart=always -it -d -v /root/openmaptiles/data:/data -p 8080:8080 maptiler/tileserver-gl
    3219b5dcd97a182b101a6fa06f05eefb13e7f0b573b58b3ce4ffe9394d4469ee
    root@vmi1046457:~# docker ps
    CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                            PORTS                    NAMES
    3219b5dcd97a   maptiler/tileserver-gl   "/usr/src/app/docker…"   9 seconds ago   Up 3 seconds (health: starting)   0.0.0.0:8080->8080/tcp   adoring_shamir
    root@vmi1046457:~# docker ps
    CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                             PORTS                    NAMES
    3219b5dcd97a   maptiler/tileserver-gl   "/usr/src/app/docker…"   35 seconds ago   Up 28 seconds (health: starting)   0.0.0.0:8080->8080/tcp   adoring_shamir
    root@vmi1046457:~# docker ps
    CONTAINER ID   IMAGE                    COMMAND                  CREATED              STATUS                        PORTS                    NAMES
    3219b5dcd97a   maptiler/tileserver-gl   "/usr/src/app/docker…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:8080->8080/tcp   adoring_shamir
    root@vmi1046457:~# 

and now it works fine: 

![image](https://user-images.githubusercontent.com/70313067/203551508-eb3c50a1-e675-4862-9b74-9ef6f6aa9a28.png)

**Comment by acalcutt** [comment]
This was just changed last week, so not to suprising there are some articles out there that need updating.

the lower port 80 caused issues with some environments, so it was changed to 8080 to improve those issues and be more consistent.

**Comment by raphael10-collab** [comment]
@acalcutt I've just informed the writer of that post of this brand new change

Thank you again for your prompt kind help

**Comment by vinayakkulkarni** [comment]
@raphael10-collab:

if you have problems (especially in larger organisations where changing ports require going through a lot of bureaucracy) of changing port bindings (host:container) 8080:8080, you can always do this:

```sh
$ sudo docker run --restart=always -it -d -v /root/openmaptiles/data:/data -p 8080:80 maptiler/tileserver-gl -p 80
```

**Comment by zstadler** [comment]
> @raphael10-collab:
> 
> if you have problems (especially in larger organisations where changing ports require going through a lot of bureaucracy) of changing port bindings (host:container) 8080:8080, you can always do this:
> 
> ```shell
> $ sudo docker run --restart=always -it -d -v /root/openmaptiles/data:/data -p 8080:80 maptiler/tileserver-gl -p 80
> ```

Unfortunately, this setup would make the docker container seem unhealthy, although it is working fine. See #651.

**Comment by scara** [comment]
Hi @zstadler and @acalcutt,
> Unfortunately, this setup would make the docker container seem unhealthy, although it is working fine. See https://github.com/maptiler/tileserver-gl/pull/651.

we could improve the [current code](https://github.com/maptiler/tileserver-gl/blob/c134795b8113b4bb676e0237ce4a681d6097f67a/src/healthcheck.js#L5):
```js
var url = 'http://localhost:8080/health';
```
by means of an environment variable which defaults to `8080`: that env var should be set whenever the option `--port` will be used.
We can go further and use that env var to force the option without using that option too.

Kind of changing the code below (untested):
```js
  .option('-p, --port <port>', 'Port [8080]', 8080, parseInt)
```
[to](https://github.com/tj/commander.js/blob/02a124c7d58dbae2ef11f9284b2c68ad94f6dc8b/examples/options-env.js#L6-L9):
```js
  .addOption(new Option('-p, --port <port>', 'Port [8080]')
    .default(8080)
    .argParser(parseInt)
    .env('TILESERVERGL_PORT') // Priority order of option values is default < env < cli
);
```
If someone will set the ENV VAR "globally" everything will work as expected since _TileServer GL_ and the health check script will see the ENV VAR.
Just a quick hacky idea.

Otherwise we could write a _pid_ file containing the TCP port (e.g. a JSON file with the options used to run the server) and the _healthcheck_ script will check for the availability of that file and will read the port from there.

HTH,
Matteo

**Comment by zstadler** [comment]
If such an environment variable is not set automatically, then I believe the recommended approach is simpler.

I doubt that such an environment variable can set automatically. I'm not familiar with a way for the tileserver-gl node process to set an environment variable based on the `--port` option, that the healthcheck process could see.

It is possible, I believe, for the tileserver-gl node process to write its port number to a file that the healthcheck process can read. Please feel free to send a PR.
