### ISSUE TITLE
viewer template looks different in docker v4.2.0

### ISSUE THREAD

**Issue by freedomlang** [maptiler/tileserver-gl#650]
Currently the viewer template in source code, do not request scaled tiles if it is on retina display. But the docker image(v4.2.0) does request scaled tiles.

I just check that html response, looks like the docker image is using a different viewer template than source code.

**Comment by acalcutt** [comment]
They should be the same. The source code is basically checkout out from the repo and built using the commands in https://github.com/maptiler/tileserver-gl/blob/master/PUBLISHING.md

If you go to the main page, does it say the same version at the bottom of the page?

**Comment by vinayakkulkarni** [comment]
Can confirm that the latest docker image pushed on [Dockerhub](https://hub.docker.com/r/maptiler/tileserver-gl/tags) & [npm](https://www.npmjs.com/package/tileserver-gl?activeTab=versions) is v4.2.0 whereas the latest version on GitHub repo is [4.2.1](https://github.com/maptiler/tileserver-gl/blob/master/package.json#L3)

@acalcutt, it seems some of the commands/steps from `PUBLISHING.md` failed / skipped during releasing `v4.2.1` ?

**Comment by acalcutt** [comment]
I don't think ive made a release for v4.2.1 yet, but the viewer should not have changed in that version. the main change so far in v4.2.1 is the healthcheck

**Comment by acalcutt** [comment]
can you tell me what code was missing from the template. to be honest this part of the code, which mentions retna, never made sense to me https://github.com/maptiler/tileserver-gl/blob/master/public/templates/viewer.tmpl#L84-L87

It's possible I removed something when I moved that template to leaflet, so it could be something we could put back.

**Comment by acalcutt** [comment]
I'm going to close this since there has been several new release and we now have a consistent workflow for release. If there is still an issue we can re-open this.
