### ISSUE TITLE
I need to create a new Style in a docker version

### ISSUE THREAD

**Issue by heyjoja** [maptiler/tileserver-gl#700]
Hi, I install the dockerized version maptiler/tileserver-gl from the docker hub, someone can help me with a documentation or any reference about how create a new style with x/y/z on docker because I don't understand where is saved the config.json

**Comment by acalcutt** [comment]
In the command 
`docker run --rm -it -v $(pwd):/data -p 8080:8080 maptiler/tileserver-gl`
the "$(pwd)" is the local path where your config would go. If you leave it $(pwd) it is whatever folder you run the command from. You can also change it to a real local path. for example, if your config files are in /opt/tileserver you could put /opt/tileserver:/data

For what to put into the config, take a look at the test file https://github.com/maptiler/tileserver-gl/releases/download/v1.3.0/test_data.zip , which shows how you would lay out the config and style folders. 

In the eaxmple on the main page you can see it just downloads this file, extracts it to the local folder, and starts tileserver. when tileserver starts it sees the config.json in the directory and uses that.
```
wget https://github.com/maptiler/tileserver-gl/releases/download/v1.3.0/test_data.zip
unzip test_data.zip
docker run --rm -it -v $(pwd):/data -p 8080:8080 maptiler/tileserver-gl
[in your browser, visit http://[server ip]:8080]
```

**Comment by acalcutt** [comment]
Good to hear 👍 I'll close this issue.
