### ISSUE TITLE
Run problem

### ISSUE THREAD

**Issue by prancius** [maptiler/tileserver-gl#731]
Any ideas what is wrong? Fresh install of ubuntu 22.04
![paveikslas](https://user-images.githubusercontent.com/13869553/214852939-51261867-83d9-446a-8a91-06f6cb0664ee.png)

**Comment by acalcutt** [comment]
If you are running natively you need Native dependencies[¶](https://maptiler-tileserver.readthedocs.io/en/latest/installation.html#native-dependencies) installed

On Ubuntu 20.04 I think libGLX.so.0 comes from the libgles2-mesa-dev package.

**Comment by prancius** [comment]
Anybody has success with ubuntu 22,04
![paveikslas](https://user-images.githubusercontent.com/13869553/214860086-7ec473c0-fa12-4486-83e4-43ba73b6bcec.png)

**Comment by acalcutt** [comment]
No, as far as we've tested 22.04 is not possible right now natively unless you [build your own maplibre-native binaries](https://github.com/maptiler/tileserver-gl/issues/643#issuecomment-1323169811). you can still use the docker version on ububtu 22.04

The current maplibre-native has a hard dependency on libicu66 but ubuntu 22.04 has libicu70. you may also be able to uninstall libicu70 and install libicu66 from http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb

**Comment by acalcutt** [comment]
btw 'libgles2-mesa-dev' needs to be installed with apt not npm

apt install libgles2-mesa-dev

**Comment by acalcutt** [comment]
That is determined `$(pwd):/data` part of the command, the part before the colon is the local path where you mbtiles/config would be. In the documented command we use $(pwd), so that would be the folder you run the command from. you could also but a real path there, like `/opt/path/to/config:/data`

**Comment by prancius** [comment]
I return to docker variant
![image](https://github.com/maptiler/tileserver-gl/assets/13869553/d59d4f1e-8cde-4f98-9203-89ad09e689f8)

Any ideas whats wrong?

**Comment by acalcutt** [comment]
if you aren't specifying your own mbtiles file it tries to download the default mbtiles files to /data/ , which from your command you are mapping to the current directory you are in ${pwd}.

Because you are running in docker, it is running as a node user that doesn't have permission to write to your local path.

The quick solution is to download the mbtiles file to the directory yourself before running tileserver-gl, with
`wget https://github.com/maptiler/tileserver-gl/releases/download/v1.3.0/zurich_switzerland.mbtiles`

you can see that in https://github.com/maptiler/tileserver-gl#getting-started-with-node

**Comment by prancius** [comment]
As you can see --mbtiles is defined in command at the end

**Comment by acalcutt** [comment]
did you do the wget part though? is that 'zurich_switzerland.mbtiles' in your current directory?

**Comment by prancius** [comment]
He, yes. This can be noticed in picture

**Comment by acalcutt** [comment]
Like I was saying, in your command, the part "$(pwd):/data" in the command tells docker to map your local folder $(pwd) to a folder inside the docker image at /data. $(pwd) in your screenshot is /home/prancious , so it is not finding the mbtiles file there.

you can do either one of the following
1.) change directory to /data before running the docker command. this will ensure your $(pwd) points to that folder that has your mbtiles file

2,) change the "$(pwd):/data" part of the command to have the folder that contains your mbtiles file on the left side of ":", like
`docker run --rm -it -v /data:/data -p 8080:8080 maptiler/tileserver-gl --mbtiles`
(the left side of the colon in the local path, the right side is the path inside the docker image which should always be /data)

**Comment by acalcutt** [comment]
Just an FYI, as of [v4.8.0 ](https://github.com/maptiler/tileserver-gl/releases/tag/v4.8.0), tileserver-gl should natively work on ubuntu 22.04. In this release there are updated linux binaries build on Ubuntu 22.04.
