### ISSUE TITLE
3D view in maplibre

### ISSUE THREAD

**Issue by utagawal** [maptiler/tileserver-gl#758]
In the native viewer of Tileserver-GL (the index page) would it be possible to have 3D view if the sources contains terrain-rgb DEM data ?

**Comment by acalcutt** [comment]
Right now, you could add a terrain layer into your style, like
https://github.com/maplibre/demotiles/blob/gh-pages/styles/osm-bright-gl-terrain/style.json#L5224-L5227

I thought in the past about having a toggle button if a raster-dem existed in sources, but you would have to know the name of the layer. maybe in javascript we could iterate though raster-dem sources and make a button for each of them.

**Comment by utagawal** [comment]
@acalcutt as always many thanks for the quick reply. We already have the terrain source in our style hence the request.

If we are using the Terrain entry in our json like this :
`"terrain": {
		"source": "TerrainSource",
		"exaggeration": 1
	}`

Would it be possible for the maplibre viewer embedded in tileserver-gl to detect it and enable the 3D view ?

**Comment by acalcutt** [comment]
I'm not talking about a terrain source, but a terrain layer (like at the very end of the [file I linked](https://github.com/maplibre/demotiles/blob/gh-pages/styles/osm-bright-gl-terrain/style.json#L5224-L5227)). It lets maplibre-gl-js to show the terrain.

**Comment by acalcutt** [comment]
nevermind, it looks like you already have it. Are you talking about vector viewer or raster? vector/view pages should show terrain. raster/rendered ones can not because maplibre-native does not yet tupport 3d terrain.

**Comment by acalcutt** [comment]
Take this as an example ( https://tiles.wifidb.net/styles/WDB_ATV/#12.33/46.11406/8.27133/-24/58 )

With the terrain source and layer, terrain does show in viewer.

**Comment by utagawal** [comment]
Not successful so far with that : https://maps.utagawavtt.com/styles/utagawavtt/style.json
Any idea ?




    Le vendredi 10 février 2023 à 16:31:03 UTC+1, Andrew Calcutt ***@***.***> a écrit :  
 
 


Take this as an example ( https://tiles.wifidb.net/styles/WDB_ATV/#12.33/46.11406/8.27133/-24/58 )

With the terrain source and layer, terrain does show in viewer.

**Comment by acalcutt** [comment]
I don't see the terrain layer I mentioned in your style. I do see a 'world-rgb-png' source, but its not used for terrain.

**Comment by acalcutt** [comment]
Your style is confusing to me. how come you link to other rendered sources?

**Comment by acalcutt** [comment]
Do you have an actual terrainrgb/terrarium raster-dem somewhere?

**Comment by utagawal** [comment]
I have put this at the end :

|  "terrain": { |
|  |  "source": "relief-france-hd", |
|  |  "exaggeration": 2 |
|  |  }, |


Where in source :

| "sources": { |
|  |  "contours": { |
|  |  "type": "vector", |
|  |  "url": "https://maps.utagawavtt.com/data/europe-contours-copernicus.json" |
|  |  }, |
|  |  "natural-earth-2": { |
|  |  "type": "raster", |
|  |  "maxzoom": 6, |
|  |  "tiles": [ |
|  |  "https://maps.utagawavtt.com/tiles/naturalearth2/{z}/{x}/{y}.png" |
|  |  ] |
|  |  }, |
|  |  "openmaptiles": { |
|  |  "type": "vector", |
|  |  "url": "https://maps.utagawavtt.com/data/planet.json" |
|  |  }, |
|  |  "world-rgb-png": { |
|  |  "type": "raster-dem", |
|  |  "minzoom": 5, |
|  |  "maxzoom": 11, |
|  |  "encoding": "terrarium", |
|  |  "tiles": ["https://maps.utagawavtt.com/tiles/world/{z}/{x}/{y}.png"] |
|  |  }, |
|  |  "relief-france-hd": { |
|  |  "type": "raster-dem", |
|  |  "tiles": [ |
|  |  "https://maps.utagawavtt.com/tiles/terrain/qLmVTMkBjTdY3g83aF5gukd3nM8v8Cn8NE9kScXi/v1/{z}/{x}/{y}.png" |
|  |  ], |
|  |  "minzoom": 6, |
|  |  "maxzoom": 15 |
|  |  }, |
|  |  "hillshade-mapzen": { |
|  |  "type": "raster", |
|  |  "tiles": [ |
|  |  "https://maps.utagawavtt.com/styles/hillshade-mapzen/{z}/{x}/{y}.png" |
|  |  ], |
|  |  "minzoom": 5, |
|  |  "maxzoom": 14 |
|  |  }, |
|  |  "hillshade-HD": { |
|  |  "type": "raster", |
|  |  "tiles": [ |
|  |  "https://maps.utagawavtt.com/styles/hillshade-HD/{z}/{x}/{y}.png" |
|  |  ], |
|  |  "minzoom": 5, |
|  |  "maxzoom": 15 |
|  |  } |
|  |  }, |



we're back-using tilerserver-gl rendered terrain sources for hillshading reasons. Tileserver-gl does rasterization that in a very good way from terrain-RGB, and since we are using the map from openlayer where the ol-mapbox-style plugin is not 100% compatible with mapbox rendering, especially with hillshading that was the hack we implemented. This is also usefull for performnace reason where the calculation to interpret terrain-rgb is done from a server side and then raster tiles are cached on server improving very much the display performance on the client.

    Le vendredi 10 février 2023 à 17:30:35 UTC+1, Andrew Calcutt ***@***.***> a écrit :  
 
 


Your style is confusing to me. how come you link to other rendered sources?

**Comment by utagawal** [comment]
Made it working (issue was the style was not refreshed as expected du to the recent implementation of nginx cache).

However I see the 3D camera pitch is kind of limited (also in your example), any reason why ?

**Comment by acalcutt** [comment]
Do you mean the 60 degree pitch limit? it is a maplibre-gl-js default, we would have to change the view template so it sets the 'maxPitch' [map option](https://maplibre.org/maplibre-gl-js-docs/api/map/)

<html>
<body>


options.maxPitch default: 60 | The maximum pitch of the map (0-85). Values greater than 60 degrees are experimental and may result in rendering issues. If you encounter any, please raise an issue with details in the MapLibre project.
-- | --



</body>
</html>

**Comment by utagawal** [comment]
`Do you mean the 60 degree pitch limit? `
Exactly

`we would have to change the view template so it sets the 'maxPitch' [map option](https://maplibre.org/maplibre-gl-js-docs/api/map/)`
Any possibility to have this option ? 60° is very restrictive.

**Comment by acalcutt** [comment]
I don't think it is a good idea until maplibre-gl-js 3.0 is released which has perfomance updates for terrain. The extra angle makes the map have to load a lot more, so this performance is important. Right now above 60deg is considered experimental.

**Comment by utagawal** [comment]
Maplibre 3.0 has been released ! :-)
