### ISSUE TITLE
Restarting container with docker restart <> results in xvfb error

### ISSUE THREAD

**Issue by a14stoner** [maptiler/tileserver-gl#794]
I deployed a tileserver-gl with the following image:  maptiler/tileserver-gl:v4.4.8

docker run -dt --name tileserver-gl -h tileserver-gt -v $(pwd):/data -p 9999:8080 maptiler/tileserver-gl:v4.4.8

When restarting the container because i changed the configuration the following error occurs: 

```
(EE) 
Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
(EE) 
Starting tileserver-gl v4.4.9
Using specified config file from config.json
Starting server
Listening at http://[::]:8080/
Startup complete
```
tileserver-gl doesnt work then anymore. 

There fore i created the pullrequest to fix this: 

https://github.com/maptiler/tileserver-gl/pull/790

**Comment by acalcutt** [comment]
With this error does tileserver still work? I assume this happens because XVFB is already running on that display when it tries to start again, Maybe instead of deleting this file we should put in a check if xvfb is running before trying to start it again. Maybe something like https://askubuntu.com/a/60593

**Comment by acalcutt** [comment]
@zstadler I know you went away from xvfb-run in the entrypoint file, but do you think it may work better in the case of a restart like this?

**Comment by zstadler** [comment]
@a14stoner ,
Please reload the configuration as described [in the documentation](https://maptiler-tileserver.readthedocs.io/en/latest/usage.html#reloading-the-configuration)

**Comment by acalcutt** [comment]
Fixed by https://github.com/maptiler/tileserver-gl/pull/790
