### ISSUE TITLE
Using tileserver-gl to serve vector tiles to android app using maplibre-gl-native

### ISSUE THREAD

**Issue by AmirOsman2020** [maptiler/tileserver-gl#800]
Hello, I recently installed tileserver-gl on my ubuntu-20.04 using the docker container and mbtiles data source I got from https://data.maptiler.com/downloads/tileset/osm/, then I used it to serve vector tiles to my android app I built using android studio, kotlin and maplibre-gl-native, everything working perfectly only some labels and names are missing specifically Arabic labels and names they don't show up, here is a screenshot of the app:

![Screenshot_20230314_140930_com clone uberclone](https://user-images.githubusercontent.com/90759789/225253431-716ecf53-046c-4926-b16e-a445bca6a89d.jpg)

I wonder what's the problem, why Arabic names don't show up and is there a way to fix this?

**Comment by acalcutt** [comment]
Typically that means you don't have a font in your fonts folder. For example, we have had similar issues with chinese characters when the noto-sans fonts are missing.

What font does your style use for these? if you look at the tileserver log you should see something about missing fonts.

**Comment by acalcutt** [comment]
Similar to https://github.com/maptiler/tileserver-gl/issues/621

**Comment by k0shTm** [comment]
@AmirOsman2020 can I ask you if the map is fluid? I have the same implementation but majority of times the map show white squares while rendering the tiles.
Did you tune up any configs from the docker example or you just run it as it is?
