### ISSUE TITLE
Does tilesever-gl does not support vector data type any more?

### ISSUE THREAD

**Issue by abozhang** [maptiler/tileserver-gl#812]
the demo url is http://47.92.237.155:9001/
I installed tileserver-gl docker to host my mbtiles file for several months, and it works well.
but recently, I got 404 error.

GET /data/hongnanshanzhai4/18/210433/104874.png 404 181 - 1.774 ms
GET /data/hongnanshanzhai4/18/210432/104874.png 404 181 - 0.410 ms
GET /data/hongnanshanzhai4/18/210432/104875.png 404 181 - 0.344 ms
GET /data/hongnanshanzhai4/18/210434/104874.png 404 181 - 0.512 ms
GET /data/hongnanshanzhai4/18/210433/104873.png 404 181 - 0.287 ms
GET /data/hongnanshanzhai4/18/210433/104875.png 404 181 - 0.217 ms
GET /data/hongnanshanzhai4/18/210435/104874.png 404 181 - 0.299 ms
GET /data/hongnanshanzhai4/18/210434/104875.png 404 181 - 0.278 ms
GET /data/hongnanshanzhai4/18/210435/104875.png 404 181 - 0.367 ms
GET /data/hongnanshanzhai4/18/210432/104873.png 404 181 - 0.281 ms
GET /data/hongnanshanzhai4/18/210435/104873.png 404 181 - 0.214 ms
GET /data/hongnanshanzhai4/19/420867/209748.png 404 181 - 0.227 ms
GET /data/hongnanshanzhai4/19/420867/209749.png 404 181 - 0.262 ms
GET /data/hongnanshanzhai4/18/210434/104873.png 404 181 - 0.294 ms
GET /data/hongnanshanzhai4/19/420868/209748.png 404 181 - 0.346 ms
GET /data/hongnanshanzhai4/19/420866/209748.png 404 181 - 0.280 ms
GET /data/hongnanshanzhai4/19/420868/209749.png 404 181 - 0.421 ms
GET /data/hongnanshanzhai4/19/420866/209749.png 404 181 - 0.215 ms
GET /data/hongnanshanzhai4/20/841735/419497.png 404 181 - 0.353 ms
GET /data/hongnanshanzhai4/20/841734/419497.png 404 181 - 0.393 ms
GET /data/hongnanshanzhai4/20/841735/419496.png 404 181 - 1.316 ms
GET /data/hongnanshanzhai4/20/841734/419496.png 404 181 - 0.232 ms
GET /data/hongnanshanzhai4/20/841734/419498.png 404 181 - 0.254 ms
GET /data/hongnanshanzhai4/20/841735/419498.png 404 181 - 0.303 ms
GET /data/hongnanshanzhai4/20/841736/419497.png 404 181 - 0.557 ms
GET /data/hongnanshanzhai4/20/841733/419496.png 404 181 - 0.392 ms
GET /data/hongnanshanzhai4/20/841733/419497.png 404 181 - 0.371 ms
GET /data/hongnanshanzhai4/20/841736/419498.png 404 181 - 0.285 ms
GET /data/hongnanshanzhai4/20/841733/419498.png 404 181 - 0.228 ms
GET /data/hongnanshanzhai4/20/841736/419496.png 404 181 - 0.262 ms
GET /data/hongnanshanzhai4/17/105216/52437.png 404 180 - 0.960 ms
GET /data/hongnanshanzhai4/17/105217/52437.png 404 180 - 0.423 ms
GET /data/hongnanshanzhai4/16/52608/26218.png 404 179 - 0.323 ms
GET /data/hongnanshanzhai4/15/26304/13109.png 404 179 - 0.392 ms
GET /data/hongnanshanzhai4/14/13152/6554.png 404 178 - 0.454 ms
GET /data/hongnanshanzhai4/13/6576/3277.png 404 177 - 0.374 ms
GET /data/hongnanshanzhai4/12/3288/1638.png 404 177 - 0.380 ms
GET /data/hongnanshanzhai4/11/1644/819.png 404 176 - 0.436 ms
GET /data/hongnanshanzhai4/10/822/409.png 404 175 - 1.600 ms

and I got a warn info :
WARN: MBTiles not in "openmaptiles" format. Serving raw data only...

I do not change the mbtiles file, is there any update?

**Comment by acalcutt** [comment]
Do you know what version of tileserver worked with this file?

**Comment by acalcutt** [comment]
Can you provide the file you are using?

**Comment by abozhang** [comment]
> Can you provide the file you are using?

Thank you so much! 
of course!  I can, but the file is too big(29MB), could not be reply directly, could you give me a email address? I send to your email.

**Comment by abozhang** [comment]
> Can you provide the file you are using?

I upload to a machine, its link is http://8.136.215.3/data.zip
I have tryed to download it, but I do not know whether you can access it or not.

**Comment by abozhang** [comment]
> Do you know what version of tileserver worked with this file? Your demo is using a very old version....2.5.0, release in 2018. were you using an older version than that before?

I have tried v2.6.0 v2.5.0 v2.4.0 v2.3.1 v2.3.0 v2.2.0
all the same result.

**Comment by abozhang** [comment]
> Can you provide the file you are using?

I upload to google drive, the link is 
https://drive.google.com/file/d/1BCdO2Z1U3uVWfMU52SUy9imPbptU94lJ/view?usp=share_link

**Comment by acalcutt** [comment]
I checked out your file and it should be noted that this is not a vector tile file, but a raster file. It seems because the mbtiles file is missing "format" in the metadata, it is choosing the wrong format.

I opened your file with [Sqlite DB Browser](https://sqlitebrowser.org/) and looked at the metadata table and you can see "format" was not in there. I added it in like this
![image](https://user-images.githubusercontent.com/3792408/227527826-ce861586-d0d5-475e-ad82-66128527ff16.png)

Once doing that, your mbtiles file works.
https://tiles.wifidb.net/data/zhongnanshanzhai_block/#14/33.82130/108.97760

You can also see in the tilejson in now correctly shows a png extension on the files instead of a pbf extension.

btw, in DB Browser you can tell this is a raster tile by going into the tiles table and clicking any of the "BLOB" data. you can see it shows an image. If this were vector tiles, this wouldn't be an image.
![image](https://user-images.githubusercontent.com/3792408/227528482-8863a92a-5635-4f82-87e8-506efa0a5027.png)

**Comment by abozhang** [comment]
> I will test with the file you provided, but it should be noted you seem to be using the wrong version. you should be using maptiler/tileserver-gl , but it seems like you are installing klokantech/tileserver-gl.
> 
> The maptiler version starts at 3.x and goes to 4.4.10 right now. 2.x klokantech versions are very old

I tried both maptiler/tileserver-gl and klokantech/tileserver-gl. 
https://github.com/klokantech/tileserver-gl will redirect to https://github.com/maptiler/tileserver-gl
so I thought it was the same project in different stages.
And I will turn to use maptiler/tileserver-gl.
Thank you so much.

**Comment by abozhang** [comment]
> I checked out your file and it should be noted that this is not a vector tile file, but a raster file. It seems because the mbtiles file is missing "format" in the metadata, it is choosing the wrong format.
> 
> I opened your file with [Sqlite DB Browser](https://sqlitebrowser.org/) and looked at the metadata table and "format" was not in there. I added it in like this ![image](https://user-images.githubusercontent.com/3792408/227527826-ce861586-d0d5-475e-ad82-66128527ff16.png)
> 
> Once doing that, your mbtiles file works. https://tiles.wifidb.net/data/zhongnanshanzhai_block/#14/33.82130/108.97760
> 
> You can also see in the tilejson in now correctly shows a png extension on the files instead of a pbf extension.
> 
> btw, in DB Browser you can tell this is a raster tile by going into the tiles table and clicking any of the "BLOB" data. you can see it shows a png image. If this were vector tiles, this wouldn't be an image. ![image](https://user-images.githubusercontent.com/3792408/227528482-8863a92a-5635-4f82-87e8-506efa0a5027.png)

Thank you so much! I will go to modfiy the mbtiles file as you said. Thank you very much!
The interesting thing is that I did not change the mbtiles file this time but just relaunched the klokantech/tileserver-gl docker, maybe it is because of the version missmatch, I will check them one by one.
Anyway, I will turn to use maptiler/tileserver-gl docker.
And I will post the last link after I fix it.

Thank you very much!

**Comment by abozhang** [comment]
it worked! when i modify the format, it goes well.
http://47.92.237.155:9001/
http://47.92.237.155:9002/
thank you very much! @acalcutt

**Comment by acalcutt** [comment]
Glad to hear this work for you. I'll close this issue. 

It seems pbf is the default format if a format doesn't exist. that somewhat makes sense since vector tiles are the main focus of tileserver-gl. If it was different in the past I'm not really sure.
