### ISSUE TITLE
SQLITE_CANTOPEN when reading data downloaded with Docker ADD

### ISSUE THREAD

**Issue by TangoYankee** [maptiler/tileserver-gl#920]
# Description:
I am [attempting](https://github.com/TangoYankee/basemap-server/blob/main/Dockerfile) to use the docker image [ADD](https://docs.docker.com/engine/reference/builder/#add) functionality to place mbtiles into the docker image. 

```
FROM maptiler/tileserver-gl:v4.4.10

COPY ./config.json /data

ARG DOWNLOAD_TOKEN
ADD https://data.maptiler.com/download/$DOWNLOAD_TOKEN/maptiler-osm-2020-02-10-v3.11-us_rhode-island.mbtiles /data

EXPOSE 8080
```
When running a container from the resulting image, it fails with the following error:

```sh
Starting tileserver-gl v4.4.10
Using specified config file from config.json
Starting server
Listening at http://[::]:8080/
Error: MBTiles not yet loaded
    at MBTiles.getInfo (/usr/src/app/node_modules/@mapbox/mbtiles/lib/mbtiles.js:252:37)
    at file:///usr/src/app/src/serve_rendered.js:1425:33
    at Database.<anonymous> (/usr/src/app/node_modules/@mapbox/mbtiles/lib/mbtiles.js:81:25)
SQLITE_CANTOPEN: unable to open database file
```
## Troubleshooting
To confirm that the tiles themselves are not causing issues, I also downloaded them directly onto my local machine and then used the `COPY` command. The tileserver successfully runs with this technique.

To confirm the `ADD` command was downloading the files as expected, I finagled the setup (downloading files with `ADD` that the tileserver config was not looking for) so that I could exec into the running container. Looking in the running container, I confirmed the files were in the expected directory with the expected name, ie) `/data/maptiler-osm-2020-02-10-v3.11-us_rhode-island.mbtiles`.

## Setup details
The repo where I'm exploring this setup has the minimally reproducible code. The troublesome `ADD` configuration is at the [head of main](https://github.com/TangoYankee/basemap-server). The working `COPY` configuration is [one commit back](https://github.com/TangoYankee/basemap-server/tree/f8208b99fe4025584d9cc8ca67e139d9af952c1d)

**Comment by scara** [comment]
Hi @TangoYankee,
I guess that it is a permission issue since the user at runtime is not the same as at build time.
I'd download a file via `curl` and fix the permissions i.e. using `RUN` and not `ADD`.

HTH,
Matteo

**Comment by TangoYankee** [comment]
Thank you for the lead. I gave [`RUN`](https://github.com/TangoYankee/basemap-server/blob/a28d15c08a555ffed9eb34a16be49b9e4345f056/Dockerfile#L7) the ole college try with curl and wget. 

```
RUN wget https://data.maptiler.com/download/$DOWNLOAD_TOKEN/maptiler-osm-2020-02-10-v3.11-us_rhode-island.mbtiles
``` 

It seems to open a new can of worms. First, neither `wget` nor `curl` seem to be included by default
```
#0 0.385 /bin/bash: wget: command not found
------
Dockerfile:7
--------------------
   5 |     
   6 |     ARG DOWNLOAD_TOKEN
   7 | >>> RUN wget https://data.maptiler.com/download/$DOWNLOAD_TOKEN/maptiler-osm-2020-02-10-v3.11-us_rhode-island.mbtiles
   8 |     
   9 |     EXPOSE 8080
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c wget https://data.maptiler.com/download/$DOWNLOAD_TOKEN/maptiler-osm-2020-02-10-v3.11-us_rhode-island.mbtiles" did not complete successfully: exit code: 127
```

I attempted to [install](https://github.com/TangoYankee/basemap-server/blob/2b8824e59ed778f30a44f70a463f3f6f867500fc/Dockerfile#L5C1-L6C25) them
```
RUN apt-get update && apt-get upgrade
RUN apt-get install wget
```

and there is another permission issue:
```
 > [3/5] RUN apt-get update && apt-get upgrade:
#0 0.300 Reading package lists...
#0 0.308 E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
------
Dockerfile:5
--------------------
   3 |     COPY ./config.json /data
   4 |     
   5 | >>> RUN apt-get update && apt-get upgrade
   6 |     RUN apt-get install wget
   7 |     
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c apt-get update && apt-get upgrade" did not complete successfully: exit code: 100
```

I do think there is something to the file permission issue. I am wondering whether the [chown/chmod feature of ADD](https://docs.docker.com/engine/reference/builder/#add) may be helpful? Though, the permission/user structure of docker images can feel opaque at times. Would someone on the tilesever-gl team have insight on how to assign permissions? ie)
```
ADD [--chown=<user>:<group>] [--chmod=<perms>] [--checksum=<checksum>] <src>... <dest>
ADD [--chown=<user>:<group>] [--chmod=<perms>] ["<src>",... "<dest>"]
```

**Comment by scara** [comment]
Hi @TangoYankee,
that's strange 'cause at least `wget` can be installed as per: https://github.com/maptiler/tileserver-gl/blob/a7e5d0b5995a3e4b24fd02ee310c9ea2538a0041/Dockerfile#L86-L92

BTW the user is `node`:https://github.com/maptiler/tileserver-gl/blob/a7e5d0b5995a3e4b24fd02ee310c9ea2538a0041/Dockerfile#L60-L63
Guessing you should get its `id` to pass it to `ADD`, running the image once - I do not have a Docker Engine right now to test it by my own.

HTH,
Matteo

**Comment by TangoYankee** [comment]
> BTW the user is node

That solved it!

[Full command](https://github.com/TangoYankee/basemap-server/blob/7af1b5af043cbb596053f6d27a1bc91f1b5b9252/Dockerfile#L6): 
```
ADD --chown=node https://data.maptiler.com/download/$DOWNLOAD_TOKEN/maptiler-osm-2020-02-10-v3.11-us_rhode-island.mbtiles /data
```
