### ISSUE TITLE
Static maps: All paths use styling of the last path

### ISSUE THREAD

**Issue by samuel-git** [maptiler/tileserver-gl#969]
I was unable to generate multiple paths with different styles in one URL.
All paths seem to use the styling of the last path (in this case ``stroke:blue``, ``width:3`` and ``fill:red``).

**URL query parameter used to generate the image below:**
```
path=stroke:yellow|width:2|fill:green|5.9,45.8|5.9,47.8|10.5,47.8|10.5,45.8|5.9,45.8&
path=stroke:blue|width:3|fill:red|4.9,44.8|4.9,46.8|9.5,46.8|9.5,44.8|4.9,44.8
```

**Resulting image:**
![750x250@2x](https://github.com/maptiler/tileserver-gl/assets/22152728/3e05ebed-0f8c-46f2-aa87-e1a79bfae44f)

**Motivation:**
The last figure in the [maptiler blogpost](https://www.maptiler.com/news/2019/01/static-maps-on-maptiler-cloud/) indicates this should be possible with tileserver.

The [maptiler API reference](https://docs.maptiler.com/cloud/api/static-maps/) also indicates using multiple path query parameter should be possible.

**Forward:**
I can give fixing this a shot but first wanted to ask if I am doing something wrong with the URL format.

**Comment by acalcutt** [comment]
I'd welcome a PR to fix it so the colors and options can be set per. I'd imagine some of the code I mentioned above would need to be moved inside this block, https://github.com/maptiler/tileserver-gl/blob/master/src/serve_rendered.js#L545-L548 , so it can set options per path.

**Comment by samuel-git** [comment]
Here is the correct pull request, splitted into two commits (fix + formatting): https://github.com/maptiler/tileserver-gl/pull/972

**Comment by acalcutt** [comment]
Fixed by https://github.com/maptiler/tileserver-gl/pull/972
