### ISSUE TITLE
Static image : polyline being truncated when containing pipe character

### ISSUE THREAD

**Issue by ouraios** [maptiler/tileserver-gl#980]
When an encoded polyline contain a pipe character to generate a static image, it apparently truncate the given encoded polyline which result into an image not representing truthfully an encoded polyline.

Example, this polyline `{{biGwvyGoUi@s_A|{@` if used with following url : `http://localhost:8080/styles/osm-liberty/static/auto/1000x1000.jpg?stroke=red&width=3&path=enc:{{biGwvyGoUi@s_A|{@`
will create this image : 
![image](https://github.com/maptiler/tileserver-gl/assets/9526860/135338fd-1a3d-4428-a1d4-599e3dca0154)

but if you give the poyline to [GeoJSON ](https://geojson.io/#map=14.33/43.61005/1.43899) it will give this stroke : 

![image](https://github.com/maptiler/tileserver-gl/assets/9526860/e28b3e19-84c7-4ebf-827a-ac5a71fc376e)

My guess is that tileserver truncate the polyline up to the pipe character and then dont take into account the second of the polyline which result in a way different stroke in generated image.

The fix would to not try splitting on pipe when an encoded polyline is given

**Comment by boldtrn** [comment]
Ok, I actually think the issue might be related to the `|` and `,`. I think the issue boils down to the decoding of the encoded polyline, we are splitting by `,` and `|`, which we should not IMHO [here](https://github.com/maptiler/tileserver-gl/blob/775ea74a2aaea8c3c838956252715c2a5e857c5e/src/serve_rendered.js#L169).

Encoded Polyline can only work if we thread the whole paramter like path parameter as one input starting with `enc:`. I can create a PR for this, if you like?
